// Generated from D:\01. TheGrasberg\Saham\1 persen juni.xlsx.
// Source columns: SHARE_CODE, ISSUER_NAME. Do not edit manually unless refreshing the source universe.
export const indonesiaStocks = [
  { ticker: "AADI", name: "ADARO ANDALAN INDONESIA Tbk" },
  { ticker: "AALI", name: "ASTRA AGRO LESTARI Tbk" },
  { ticker: "ABBA", name: "MAHAKA MEDIA Tbk" },
  { ticker: "ABDA", name: "ASURANSI BINA DANA ARTA Tbk" },
  { ticker: "ABMM", name: "ABM INVESTAMA Tbk" },
  { ticker: "ACES", name: "ASPIRASI HIDUP INDONESIA Tbk" },
  { ticker: "ACRO", name: "SAMCRO HYOSUNG ADILESTARI Tbk" },
  { ticker: "ACST", name: "ACSET INDONUSA Tbk" },
  { ticker: "ADCP", name: "ADHI COMMUTER PROPERTI Tbk" },
  { ticker: "ADES", name: "AKASHA WIRA INTERNATIONAL Tbk" },
  { ticker: "ADHI", name: "ADHI KARYA (PERSERO) Tbk" },
  { ticker: "ADMF", name: "ADIRA DINAMIKA MULTI FINANCE Tbk" },
  { ticker: "ADMG", name: "POLYCHEM INDONESIA Tbk" },
  { ticker: "ADMR", name: "ALAMTRI MINERALS INDONESIA Tbk" },
  { ticker: "ADRO", name: "ALAMTRI RESOURCES INDONESIA Tbk" },
  { ticker: "AEGS", name: "ANUGERAH SPAREPARTS SEJAHTERA Tbk" },
  { ticker: "AGAR", name: "ASIA SEJAHTERA MINA Tbk" },
  { ticker: "AGII", name: "SAMATOR INDO GAS Tbk" },
  { ticker: "AGRO", name: "BANK RAYA INDONESIA Tbk" },
  { ticker: "AGRS", name: "BANK IBK INDONESIA Tbk" },
  { ticker: "AHAP", name: "ASURANSI HARTA AMAN PRATAMA Tbk" },
  { ticker: "AIMS", name: "ARTHA MAHIYA INVESTAMA Tbk" },
  { ticker: "AISA", name: "FKS FOOD SEJAHTERA Tbk" },
  { ticker: "AKKU", name: "ANUGERAH KAGUM KARYA UTAMA Tbk" },
  { ticker: "AKPI", name: "ARGHA KARYA PRIMA INDUSTRY Tbk" },
  { ticker: "AKRA", name: "AKR CORPORINDO Tbk" },
  { ticker: "AKSI", name: "MINERAL SUMBERDAYA MANDIRI Tbk" },
  { ticker: "ALDO", name: "ALKINDO NARATAMA Tbk" },
  { ticker: "ALII", name: "ANCARA LOGISTICS INDONESIA Tbk" },
  { ticker: "ALKA", name: "ALAKASA INDUSTRINDO Tbk" },
  { ticker: "ALMI", name: "ALUMINDO LIGHT METAL INDUSTRY Tbk" },
  { ticker: "ALTO", name: "TRI BANYAN TIRTA Tbk" },
  { ticker: "AMAG", name: "ASURANSI MULTI ARTHA GUNA Tbk" },
  { ticker: "AMAN", name: "MAKMUR BERKAH AMANDA Tbk" },
  { ticker: "AMAR", name: "BANK AMAR INDONESIA Tbk" },
  { ticker: "AMFG", name: "ASAHIMAS FLAT GLASS Tbk" },
  { ticker: "AMIN", name: "ATELIERS MECANIQUES D`INDONESIE Tbk" },
  { ticker: "AMMN", name: "AMMAN MINERAL INTERNASIONAL Tbk" },
  { ticker: "AMMS", name: "AGUNG MENJANGAN MAS Tbk" },
  { ticker: "AMOR", name: "ASHMORE ASSET MANAGEMENT INDONESIA Tbk" },
  { ticker: "AMRT", name: "SUMBER ALFARIA TRIJAYA Tbk" },
  { ticker: "ANDI", name: "ANDIRA AGRO Tbk" },
  { ticker: "ANJT", name: "AUSTINDO NUSANTARA JAYA Tbk" },
  { ticker: "ANTM", name: "ANEKA TAMBANG Tbk" },
  { ticker: "APEX", name: "APEXINDO PRATAMA DUTA Tbk" },
  { ticker: "APIC", name: "PACIFIC STRATEGIC FINANCIAL Tbk" },
  { ticker: "APII", name: "ARITA PRIMA INDONESIA Tbk" },
  { ticker: "APLI", name: "ASIAPLAST INDUSTRIES Tbk" },
  { ticker: "APLN", name: "AGUNG PODOMORO LAND Tbk" },
  { ticker: "ARCI", name: "ARCHI INDONESIA Tbk" },
  { ticker: "AREA", name: "DUNIA VIRTUAL ONLINE Tbk" },
  { ticker: "ARGO", name: "ARGO PANTES Tbk" },
  { ticker: "ARII", name: "ATLAS RESOURCES Tbk" },
  { ticker: "ARKA", name: "ARKHA JAYANTI PERSADA Tbk" },
  { ticker: "ARKO", name: "ARKORA HYDRO Tbk" },
  { ticker: "ARMY", name: "ARMIDIAN KARYATAMA Tbk" },
  { ticker: "ARNA", name: "ARWANA CITRAMULIA Tbk" },
  { ticker: "ARTA", name: "ARTHAVEST Tbk" },
  { ticker: "ARTI", name: "RATU PRABU ENERGI Tbk" },
  { ticker: "ARTO", name: "BANK JAGO Tbk" },
  { ticker: "ASBI", name: "ASURANSI BINTANG Tbk" },
  { ticker: "ASDM", name: "ASURANSI DAYIN MITRA Tbk" },
  { ticker: "ASGR", name: "ASTRA GRAPHIA Tbk" },
  { ticker: "ASHA", name: "CILACAP SAMUDERA FISHING INDUSTRY Tbk" },
  { ticker: "ASII", name: "ASTRA INTERNATIONAL Tbk" },
  { ticker: "ASJT", name: "ASURANSI JASA TANIA Tbk" },
  { ticker: "ASLC", name: "AUTOPEDIA SUKSES LESTARI Tbk" },
  { ticker: "ASLI", name: "ASRI KARYA LESTARI Tbk" },
  { ticker: "ASMI", name: "ASURANSI MAXIMUS GRAHA PERSADA Tbk" },
  { ticker: "ASPI", name: "ANDALAN SAKTI PRIMAINDO Tbk" },
  { ticker: "ASPR", name: "ASIA PRAMULIA Tbk" },
  { ticker: "ASRI", name: "ALAM SUTERA REALTY Tbk" },
  { ticker: "ASRM", name: "ASURANSI RAMAYANA Tbk" },
  { ticker: "ASSA", name: "ADI SARANA ARMADA Tbk" },
  { ticker: "ATAP", name: "TRIMITRA PRAWARA GOLDLAND Tbk" },
  { ticker: "ATIC", name: "ANABATIC TECHNOLOGIES Tbk" },
  { ticker: "ATLA", name: "ATLANTIS SUBSEA INDONESIA Tbk" },
  { ticker: "AUTO", name: "ASTRA OTOPARTS Tbk" },
  { ticker: "AVIA", name: "AVIA AVIAN Tbk" },
  { ticker: "AWAN", name: "ERA DIGITAL MEDIA Tbk" },
  { ticker: "AXIO", name: "TERA DATA INDONUSA Tbk" },
  { ticker: "AYAM", name: "JANU PUTRA SEJAHTERA Tbk" },
  { ticker: "AYLS", name: "AGRO YASA LESTARI Tbk" },
  { ticker: "BABP", name: "BANK MNC INTERNASIONAL Tbk" },
  { ticker: "BABY", name: "MULTITREND INDO Tbk" },
  { ticker: "BACA", name: "BANK CAPITAL INDONESIA Tbk" },
  { ticker: "BAIK", name: "BERSAMA MENCAPAI PUNCAK Tbk" },
  { ticker: "BAJA", name: "SARANACENTRAL BAJATAMA Tbk" },
  { ticker: "BALI", name: "BALI TOWERINDO SENTRA Tbk" },
  { ticker: "BANK", name: "BANK ALADIN SYARIAH Tbk" },
  { ticker: "BAPA", name: "BEKASI ASRI PEMULA Tbk" },
  { ticker: "BAPI", name: "BHAKTI AGUNG PROPERTINDO Tbk" },
  { ticker: "BATA", name: "SEPATU BATA Tbk" },
  { ticker: "BATR", name: "BENTENG API TECHNIC Tbk" },
  { ticker: "BAUT", name: "MITRA ANGKASA SEJAHTERA Tbk" },
  { ticker: "BAYU", name: "BAYU BUANA Tbk" },
  { ticker: "BBCA", name: "BANK CENTRAL ASIA Tbk" },
  { ticker: "BBHI", name: "ALLO BANK INDONESIA Tbk" },
  { ticker: "BBKP", name: "BANK KB INDONESIA Tbk" },
  { ticker: "BBLD", name: "BUANA FINANCE Tbk" },
  { ticker: "BBMD", name: "BANK MESTIKA DHARMA Tbk" },
  { ticker: "BBNI", name: "BANK NEGARA INDONESIA Tbk" },
  { ticker: "BBRI", name: "BANK RAKYAT INDONESIA (PERSERO) Tbk" },
  { ticker: "BBRM", name: "PELAYARAN NASIONAL BINA BUANA RAYA Tbk" },
  { ticker: "BBSI", name: "KROM BANK INDONESIA Tbk" },
  { ticker: "BBSS", name: "BUMI BENOWO SUKSES SEJAHTERA Tbk" },
  { ticker: "BBTN", name: "BANK TABUNGAN NEGARA (PERSERO) Tbk" },
  { ticker: "BBYB", name: "BANK NEO COMMERCE Tbk" },
  { ticker: "BCAP", name: "MNC KAPITAL INDONESIA Tbk" },
  { ticker: "BCIC", name: "BANK JTRUST INDONESIA Tbk" },
  { ticker: "BCIP", name: "BUMI CITRA PERMAI Tbk" },
  { ticker: "BDKR", name: "BERDIKARI PONDASI PERKASA Tbk" },
  { ticker: "BDMN", name: "BANK DANAMON INDONESIA Tbk" },
  { ticker: "BEBS", name: "BERKAH BETON SADAYA Tbk" },
  { ticker: "BEEF", name: "ESTIKA TATA TIARA Tbk" },
  { ticker: "BEER", name: "JOBUBU JARUM MINAHASA Tbk" },
  { ticker: "BEKS", name: "BANK PEMBANGUNAN DAERAH BANTEN Tbk" },
  { ticker: "BELI", name: "GLOBAL DIGITAL NIAGA Tbk" },
  { ticker: "BELL", name: "TRISULA TEXTILE INDUSTRIES Tbk" },
  { ticker: "BESS", name: "BATULICIN NUSANTARA MARITIM Tbk" },
  { ticker: "BEST", name: "BEKASI FAJAR INDUSTRIAL ESTATE Tbk" },
  { ticker: "BFIN", name: "BFI FINANCE INDONESIA Tbk" },
  { ticker: "BGTG", name: "BANK GANESHA Tbk" },
  { ticker: "BHAT", name: "BHAKTI MULTI ARTHA Tbk" },
  { ticker: "BHIT", name: "MNC ASIA HOLDING Tbk" },
  { ticker: "BIKA", name: "BINAKARYA JAYA ABADI Tbk" },
  { ticker: "BIKE", name: "SEPEDA BERSAMA INDONESIA Tbk" },
  { ticker: "BIMA", name: "PRIMARINDO ASIA INFRASTRUCTURE Tbk" },
  { ticker: "BINA", name: "BANK INA PERDANA Tbk" },
  { ticker: "BINO", name: "PERMA PLASINDO Tbk" },
  { ticker: "BIPI", name: "ASTRINDO NUSANTARA INFRASTRUKTUR Tbk" },
  { ticker: "BIPP", name: "BHUWANATALA INDAH PERMAI Tbk" },
  { ticker: "BIRD", name: "BLUE BIRD Tbk" },
  { ticker: "BISI", name: "BISI INTERNATIONAL Tbk" },
  { ticker: "BJBR", name: "BANK JABAR BANTEN Tbk" },
  { ticker: "BJTM", name: "BANK PEMBANGUNAN DAERAH JAWA TIMUR Tbk" },
  { ticker: "BKDP", name: "BUKIT DARMO PROPERTY Tbk" },
  { ticker: "BKSL", name: "SENTUL CITY Tbk" },
  { ticker: "BKSW", name: "BANK QNB INDONESIA Tbk" },
  { ticker: "BLES", name: "SUPERIOR PRIMA SUKSES Tbk" },
  { ticker: "BLOG", name: "TRIMITRA TRANS PERSADA Tbk" },
  { ticker: "BLTA", name: "BERLIAN LAJU TANKER Tbk" },
  { ticker: "BLTZ", name: "GRAHA LAYAR PRIMA Tbk" },
  { ticker: "BLUE", name: "BERKAH PRIMA PERKASA Tbk" },
  { ticker: "BMAS", name: "BANK MASPION INDONESIA Tbk" },
  { ticker: "BMBL", name: "LAVENDER BINA CENDIKIA Tbk" },
  { ticker: "BMHS", name: "BUNDAMEDIK Tbk" },
  { ticker: "BMRI", name: "BANK MANDIRI ( PERSERO ) Tbk" },
  { ticker: "BMSR", name: "BINTANG MITRA SEMESTARAYA Tbk" },
  { ticker: "BMTR", name: "GLOBAL MEDIACOM Tbk" },
  { ticker: "BNBA", name: "BANK BUMI ARTA Tbk" },
  { ticker: "BNBR", name: "BAKRIE AND BROTHERS Tbk" },
  { ticker: "BNGA", name: "BANK CIMB NIAGA Tbk" },
  { ticker: "BNII", name: "BANK MAYBANK INDONESIA Tbk" },
  { ticker: "BNLI", name: "BANK PERMATA Tbk" },
  { ticker: "BOAT", name: "NEWPORT MARINE SERVICES Tbk" },
  { ticker: "BOBA", name: "FORMOSA INGREDIENT FACTORY Tbk" },
  { ticker: "BOGA", name: "APOLLO GLOBAL INTERACTIVE Tbk" },
  { ticker: "BOLA", name: "BALI BINTANG SEJAHTERA Tbk" },
  { ticker: "BOLT", name: "GARUDA METALINDO Tbk" },
  { ticker: "BOSS", name: "BORNEO OLAH SARANA SUKSES Tbk" },
  { ticker: "BPFI", name: "WOORI FINANCE INDONESIA Tbk" },
  { ticker: "BPII", name: "BATAVIA PROSPERINDO INTERNASIONAL Tbk" },
  { ticker: "BPTR", name: "BATAVIA PROSPERINDO TRANS Tbk" },
  { ticker: "BRAM", name: "INDO KORDSA Tbk" },
  { ticker: "BREN", name: "BARITO RENEWABLES ENERGY Tbk" },
  { ticker: "BRIS", name: "BANK SYARIAH INDONESIA Tbk" },
  { ticker: "BRMS", name: "BUMI RESOURCES MINERALS Tbk" },
  { ticker: "BRNA", name: "BERLINA Tbk" },
  { ticker: "BRPT", name: "BARITO PACIFIC Tbk" },
  { ticker: "BRRC", name: "RAJA ROTI CEMERLANG Tbk" },
  { ticker: "BSBK", name: "WULANDARI BANGUN LAKSANA Tbk" },
  { ticker: "BSDE", name: "BUMI SERPONG DAMAI Tbk" },
  { ticker: "BSIM", name: "BANK SINAR MAS Tbk" },
  { ticker: "BSML", name: "BINTANG SAMUDERA MANDIRI LINES Tbk" },
  { ticker: "BSSR", name: "BARAMULTI SUKSESSARANA Tbk" },
  { ticker: "BSWD", name: "BANK OF INDIA INDONESIA Tbk" },
  { ticker: "BTEK", name: "BUMI TEKNOKULTURA UNGGUL Tbk" },
  { ticker: "BTEL", name: "BAKRIE TELECOM Tbk" },
  { ticker: "BTON", name: "BETONJAYA MANUNGGAL Tbk" },
  { ticker: "BTPN", name: "BANK SMBC INDONESIA Tbk" },
  { ticker: "BTPS", name: "BANK BTPN SYARIAH Tbk" },
  { ticker: "BUAH", name: "SEGAR KUMALA INDONESIA Tbk" },
  { ticker: "BUDI", name: "BUDI STARCH & SWEETENER Tbk" },
  { ticker: "BUKA", name: "BUKALAPAK.COM Tbk" },
  { ticker: "BUKK", name: "BUKAKA TEKNIK UTAMA Tbk" },
  { ticker: "BULL", name: "BUANA LINTAS LAUTAN Tbk" },
  { ticker: "BUMI", name: "BUMI RESOURCES Tbk" },
  { ticker: "BUVA", name: "BUKIT ULUWATU VILLA Tbk" },
  { ticker: "BVIC", name: "BANK VICTORIA INTERNATIONAL  Tbk" },
  { ticker: "BWPT", name: "EAGLE HIGH PLANTATIONS, Tbk" },
  { ticker: "BYAN", name: "BAYAN RESOURCES Tbk" },
  { ticker: "CAKK", name: "CAHAYAPUTRA ASA KERAMIK Tbk" },
  { ticker: "CAMP", name: "CAMPINA ICE CREAM INDUSTRY Tbk" },
  { ticker: "CANI", name: "CAPITOL NUSANTARA INDONESIA Tbk" },
  { ticker: "CARE", name: "METRO HEALTHCARE INDONESIA Tbk" },
  { ticker: "CARS", name: "INDUSTRI DAN PERDAGANGAN BINTRACO DHARMA Tbk" },
  { ticker: "CASA", name: "CAPITAL FINANCIAL INDONESIA Tbk" },
  { ticker: "CASH", name: "CASHLEZ WORLDWIDE INDONESIA Tbk" },
  { ticker: "CASS", name: "CAHAYA AERO SERVICES Tbk" },
  { ticker: "CBDK", name: "BANGUN KOSAMBI SUKSES Tbk" },
  { ticker: "CBMF", name: "CAHAYA BINTANG MEDAN Tbk" },
  { ticker: "CBPE", name: "CITRA BUANA PRASIDA Tbk" },
  { ticker: "CBRE", name: "CAKRA BUANA RESOURCES ENERGI Tbk" },
  { ticker: "CBUT", name: "CITRA BORNEO UTAMA Tbk" },
  { ticker: "CCSI", name: "COMMUNICATION CABLE SYSTEMS INDONESIA Tbk" },
  { ticker: "CDIA", name: "CHANDRA DAYA INVESTASI Tbk" },
  { ticker: "CEKA", name: "WILMAR CAHAYA INDONESIA Tbk" },
  { ticker: "CENT", name: "CENTRATAMA TELEKOMUNIKASI INDONESIA Tbk" },
  { ticker: "CFIN", name: "CLIPAN FINANCE INDONESIA Tbk" },
  { ticker: "CGAS", name: "CITRA NUSANTARA GEMILANG Tbk" },
  { ticker: "CHEK", name: "DIASTIKA BIOTEKINDO Tbk" },
  { ticker: "CHEM", name: "CHEMSTAR INDONESIA Tbk" },
  { ticker: "CHIP", name: "PELITA TEKNOLOGI GLOBAL Tbk" },
  { ticker: "CINT", name: "CHITOSE INTERNASIONAL Tbk" },
  { ticker: "CITA", name: "CITA MINERAL INVESTINDO Tbk" },
  { ticker: "CITY", name: "NATURA CITY DEVELOPMENTS Tbk" },
  { ticker: "CLAY", name: "CITRA PUTRA REALTY Tbk" },
  { ticker: "CLEO", name: "SARIGUNA PRIMATIRTA Tbk" },
  { ticker: "CLPI", name: "COLORPAK INDONESIA Tbk" },
  { ticker: "CMNP", name: "CITRA MARGA NUSAPHALA PERSADA Tbk" },
  { ticker: "CMNT", name: "CEMINDO GEMILANG Tbk" },
  { ticker: "CMPP", name: "AIRASIA INDONESIA Tbk" },
  { ticker: "CMRY", name: "CISARUA MOUNTAIN DAIRY Tbk" },
  { ticker: "CNKO", name: "EXPLOITASI ENERGI INDONESIA Tbk" },
  { ticker: "CNMA", name: "NUSANTARA SEJAHTERA RAYA Tbk" },
  { ticker: "CNTX", name: "CENTEX Tbk SERI A PREFEREN" },
  { ticker: "COAL", name: "BLACK DIAMOND RESOURCES Tbk" },
  { ticker: "COCO", name: "WAHANA INTERFOOD NUSANTARA Tbk" },
  { ticker: "COIN", name: "INDOKRIPTO KOIN SEMESTA Tbk" },
  { ticker: "COWL", name: "COWELL DEVELOPMENT Tbk" },
  { ticker: "CPIN", name: "CHAROEN POKPHAND INDONESIA Tbk" },
  { ticker: "CPRI", name: "CAPRI NUSA SATU PROPERTI Tbk" },
  { ticker: "CPRO", name: "CENTRAL PROTEINAPRIMA Tbk" },
  { ticker: "CRAB", name: "TOBA SURIMI INDUSTRIES Tbk" },
  { ticker: "CRSN", name: "CARSURIN Tbk" },
  { ticker: "CSAP", name: "CATUR SENTOSA ADIPRANA Tbk" },
  { ticker: "CSIS", name: "CAHAYASAKTI INVESTINDO SUKSES Tbk" },
  { ticker: "CSMI", name: "CIPTA SELERA MURNI Tbk" },
  { ticker: "CSRA", name: "CISADANE SAWIT RAYA Tbk" },
  { ticker: "CTBN", name: "CITRA TUBINDO Tbk" },
  { ticker: "CTRA", name: "CIPUTRA DEVELOPMENT Tbk" },
  { ticker: "CTTH", name: "CITATAH  Tbk" },
  { ticker: "CUAN", name: "PETRINDO JAYA KREASI Tbk" },
  { ticker: "CYBR", name: "ITSEC ASIA Tbk" },
  { ticker: "DAAZ", name: "DAAZ BARA LESTARI Tbk" },
  { ticker: "DADA", name: "DIAMOND CITRA PROPERTINDO Tbk" },
  { ticker: "DART", name: "DUTA ANGGADA REALTY Tbk" },
  { ticker: "DATA", name: "REMALA ABADI Tbk" },
  { ticker: "DAYA", name: "DUTA INTIDAYA Tbk" },
  { ticker: "DCII", name: "DCI INDONESIA Tbk" },
  { ticker: "DEAL", name: "DEWATA FREIGHTINTERNATIONAL Tbk" },
  { ticker: "DEFI", name: "DANASUPRA ERAPACIFIC Tbk" },
  { ticker: "DEPO", name: "CATURKARDA DEPO BANGUNAN Tbk" },
  { ticker: "DEWA", name: "DARMA HENWA Tbk" },
  { ticker: "DEWI", name: "DEWI SHRI FARMINDO Tbk" },
  { ticker: "DFAM", name: "DAFAM PROPERTY INDONESIA Tbk" },
  { ticker: "DGIK", name: "NUSA KONSTRUKSI ENJINIRING Tbk" },
  { ticker: "DGNS", name: "DIAGNOS LABORATORIUM UTAMA Tbk" },
  { ticker: "DGWG", name: "DELTA GIRI WACANA Tbk" },
  { ticker: "DIGI", name: "ARKADIA DIGITAL MEDIA Tbk" },
  { ticker: "DILD", name: "INTILAND DEVELOPMENT Tbk" },
  { ticker: "DIVA", name: "DISTRIBUSI VOUCHER NUSANTARA Tbk" },
  { ticker: "DKFT", name: "CENTRAL OMEGA RESOURCES Tbk" },
  { ticker: "DKHH", name: "CIPTA SARANA MEDIKA Tbk" },
  { ticker: "DLTA", name: "DELTA DJAKARTA Tbk" },
  { ticker: "DMAS", name: "PURADELTA LESTARI Tbk" },
  { ticker: "DMMX", name: "DIGITAL MEDIATAMA MAXIMA Tbk" },
  { ticker: "DMND", name: "DIAMOND FOOD INDONESIA Tbk" },
  { ticker: "DNAR", name: "BANK OKE INDONESIA Tbk" },
  { ticker: "DNET", name: "INDORITEL MAKMUR INTERNASIONAL Tbk" },
  { ticker: "DOID", name: "BUMA INTERNASIONAL GRUP Tbk" },
  { ticker: "DOOH", name: "ERA MEDIA SEJAHTERA Tbk" },
  { ticker: "DOSS", name: "GLOBAL SUKSES DIGITAL Tbk" },
  { ticker: "DPNS", name: "DUTA PERTIWI NUSANTARA" },
  { ticker: "DPUM", name: "DUA PUTRA UTAMA MAKMUR Tbk" },
  { ticker: "DRMA", name: "DHARMA POLIMETAL Tbk" },
  { ticker: "DSFI", name: "DHARMA SAMUDERA FISHING INDUSTRIES Tbk" },
  { ticker: "DSNG", name: "DHARMA SATYA NUSANTARA Tbk" },
  { ticker: "DSSA", name: "DIAN SWASTATIKA SENTOSA Tbk" },
  { ticker: "DUCK", name: "JAYA BERSAMA INDO Tbk" },
  { ticker: "DUTI", name: "DUTA PERTIWI Tbk" },
  { ticker: "DVLA", name: "DARYA - VARIA LABORATORIA Tbk" },
  { ticker: "DWGL", name: "DWI GUNA LAKSANA Tbk" },
  { ticker: "DYAN", name: "DYANDRA MEDIA INTERNATIONAL Tbk" },
  { ticker: "EAST", name: "EASTPARC HOTEL Tbk" },
  { ticker: "ECII", name: "ELECTRONIC CITY INDONESIA Tbk" },
  { ticker: "EDGE", name: "INDOINTERNET Tbk" },
  { ticker: "EKAD", name: "EKADHARMA INTERNATIONAL Tbk" },
  { ticker: "ELIT", name: "DATA SINERGITAMA JAYA Tbk" },
  { ticker: "ELPI", name: "PELAYARAN NASIONAL EKALYA PURNAMASARI Tbk" },
  { ticker: "ELSA", name: "ELNUSA Tbk" },
  { ticker: "ELTY", name: "BAKRIELAND DEVELOPMENT Tbk" },
  { ticker: "EMAS", name: "MERDEKA GOLD RESOURCES Tbk" },
  { ticker: "EMDE", name: "MEGAPOLITAN DEVELOPMENTS Tbk" },
  { ticker: "EMTK", name: "ELANG MAHKOTA TEKNOLOGI Tbk" },
  { ticker: "ENAK", name: "CHAMP RESTO INDONESIA Tbk" },
  { ticker: "ENRG", name: "ENERGI MEGA PERSADA Tbk" },
  { ticker: "ENVY", name: "ENVY TECHNOLOGIES INDONESIA Tbk" },
  { ticker: "ENZO", name: "MORENZO ABADI PERKASA Tbk" },
  { ticker: "EPAC", name: "MEGALESTARI EPACK SENTOSARAYA Tbk" },
  { ticker: "EPMT", name: "ENSEVAL PUTERA MEGATRADING Tbk" },
  { ticker: "ERAA", name: "ERAJAYA SWASEMBADA Tbk" },
  { ticker: "ERAL", name: "SINAR EKA SELARAS Tbk" },
  { ticker: "ERTX", name: "ERATEX DJAJA Tbk" },
  { ticker: "ESIP", name: "SINERGI INTI PLASTINDO Tbk" },
  { ticker: "ESSA", name: "ESSA INDUSTRIES INDONESIA Tbk" },
  { ticker: "ESTA", name: "ESTA MULTI USAHA Tbk" },
  { ticker: "ESTI", name: "EVER SHINE TEXTILE INDUSTRY" },
  { ticker: "ETWA", name: "ETERINDO WAHANATAMA Tbk" },
  { ticker: "EURO", name: "ESTEE GOLD FEET Tbk" },
  { ticker: "EXCL", name: "XLSMART TELECOM SEJAHTERA Tbk" },
  { ticker: "FAPA", name: "FAP AGRI Tbk" },
  { ticker: "FAST", name: "FAST FOOD INDONESIA Tbk" },
  { ticker: "FASW", name: "FAJAR SURYA WISESA Tbk" },
  { ticker: "FILM", name: "MD ENTERTAINMENT Tbk" },
  { ticker: "FIMP", name: "FIMPERKASA UTAMA Tbk" },
  { ticker: "FIRE", name: "ALFA ENERGI INVESTAMA Tbk" },
  { ticker: "FISH", name: "FKS MULTI AGRO Tbk" },
  { ticker: "FITT", name: "HOTEL FITRA INTERNATIONAL Tbk" },
  { ticker: "FLMC", name: "FALMACO NONWOVEN INDUSTRI Tbk" },
  { ticker: "FMII", name: "FORTUNE MATE INDONESIA Tbk" },
  { ticker: "FOLK", name: "MULTI GARAM UTAMA Tbk" },
  { ticker: "FOOD", name: "SENTRA FOOD INDONESIA Tbk" },
  { ticker: "FORE", name: "FORE KOPI INDONESIA Tbk" },
  { ticker: "FORU", name: "FORTUNE INDONESIA Tbk" },
  { ticker: "FPNI", name: "LOTTE CHEMICAL TITAN Tbk" },
  { ticker: "FUJI", name: "FUJI FINANCE INDONESIA Tbk" },
  { ticker: "FUTR", name: "FUTURA ENERGI GLOBAL Tbk" },
  { ticker: "FWCT", name: "WIJAYA CAHAYA TIMBER Tbk" },
  { ticker: "GAMA", name: "AKSARA GLOBAL DEVELOPMENT Tbk" },
  { ticker: "GDST", name: "GUNAWAN DIANJAYA STEEL Tbk" },
  { ticker: "GDYR", name: "GOODYEAR INDONESIA Tbk" },
  { ticker: "GEMA", name: "GEMA GRAHASARANA Tbk" },
  { ticker: "GEMS", name: "GOLDEN ENERGY MINES Tbk" },
  { ticker: "GGRM", name: "GUDANG GARAM Tbk" },
  { ticker: "GGRP", name: "GUNUNG RAJA PAKSI Tbk" },
  { ticker: "GHON", name: "GIHON TELEKOMUNIKASI INDONESIA Tbk" },
  { ticker: "GIAA", name: "GARUDA INDONESIA (PERSERO) Tbk" },
  { ticker: "GJTL", name: "GAJAH TUNGGAL Tbk" },
  { ticker: "GLOB", name: "GLOBE KITA TERANG Tbk" },
  { ticker: "GLVA", name: "GALVA TECHNOLOGIES Tbk" },
  { ticker: "GMFI", name: "GARUDA MAINTENANCE FACILITY AERO ASIA Tbk" },
  { ticker: "GMTD", name: "GOWA MAKASSAR TOURISM DEVELOPMENT Tbk" },
  { ticker: "GOLD", name: "VISI TELEKOMUNIKASI INFRASTRUKTUR Tbk, PT" },
  { ticker: "GOLF", name: "INTRA GOLFLINK RESORTS Tbk" },
  { ticker: "GOLL", name: "GOLDEN PLANTATION Tbk" },
  { ticker: "GOOD", name: "GARUDAFOOD PUTRA PUTRI JAYA Tbk" },
  { ticker: "GOTO", name: "GOTO GOJEK TOKOPEDIA Tbk" },
  { ticker: "GPRA", name: "PERDANA GAPURAPRIMA Tbk" },
  { ticker: "GPSO", name: "GEOPRIMA SOLUSI Tbk" },
  { ticker: "GRIA", name: "INGRIA PRATAMA CAPITALINDO Tbk" },
  { ticker: "GRPH", name: "GRIPTHA PUTRA PERSADA Tbk" },
  { ticker: "GRPM", name: "GRAHA PRIMA MENTARI Tbk" },
  { ticker: "GSMF", name: "EQUITY DEVELOPMENT INVESTMENT Tbk" },
  { ticker: "GTBO", name: "GARDA TUJUH BUANA Tbk" },
  { ticker: "GTRA", name: "GRAHAPRIMA SUKSESMANDIRI Tbk" },
  { ticker: "GTSI", name: "GTS INTERNASIONAL Tbk" },
  { ticker: "GULA", name: "AMAN AGRINDO Tbk" },
  { ticker: "GUNA", name: "GUNANUSA ERAMANDIRI Tbk" },
  { ticker: "GWSA", name: "GREENWOOD SEJAHTERA Tbk" },
  { ticker: "GZCO", name: "GOZCO PLANTATIONS Tbk" },
  { ticker: "HADE", name: "HIMALAYA ENERGI PERKASA Tbk" },
  { ticker: "HAIS", name: "HASNUR INTERNASIONAL SHIPPING Tbk" },
  { ticker: "HAJJ", name: "ARSY BUANA TRAVELINDO Tbk" },
  { ticker: "HALO", name: "HALONI JANE Tbk" },
  { ticker: "HATM", name: "HABCO TRANS MARITIMA Tbk" },
  { ticker: "HBAT", name: "MINAHASA MEMBANGUN HEBAT Tbk" },
  { ticker: "HDFA", name: "RADANA BHASKARA FINANCE Tbk" },
  { ticker: "HDIT", name: "HENSEL DAVEST INDONESIA Tbk" },
  { ticker: "HEAL", name: "MEDIKALOKA HERMINA Tbk" },
  { ticker: "HELI", name: "JAYA TRISHINDO Tbk" },
  { ticker: "HERO", name: "DFI RETAIL NUSANTARA Tbk" },
  { ticker: "HEXA", name: "HEXINDO ADIPERKASA Tbk" },
  { ticker: "HGII", name: "HERO GLOBAL INVESTMENT Tbk" },
  { ticker: "HILL", name: "HILLCON Tbk" },
  { ticker: "HITS", name: "HUMPUSS INTERMODA TRANSPORTASI Tbk" },
  { ticker: "HKMU", name: "HK METALS UTAMA Tbk" },
  { ticker: "HMSP", name: "HANJAYA MANDALA SAMPOERNA Tbk" },
  { ticker: "HOKI", name: "BUYUNG POETRA SEMBADA Tbk" },
  { ticker: "HOME", name: "HOTEL MANDARINE REGENCY Tbk" },
  { ticker: "HOMI", name: "GRAND HOUSE MULIA Tbk" },
  { ticker: "HOPE", name: "HARAPAN DUTA PERTIWI Tbk" },
  { ticker: "HOTL", name: "SARASWATI GRIYA LESTARI Tbk" },
  { ticker: "HRME", name: "MENTENG HERITAGE REALTY Tbk" },
  { ticker: "HRTA", name: "HARTADINATA ABADI Tbk" },
  { ticker: "HRUM", name: "HARUM ENERGY Tbk" },
  { ticker: "HUMI", name: "HUMPUSS MARITIM INTERNASIONAL Tbk" },
  { ticker: "HYGN", name: "ECOCARE INDO PASIFIK Tbk" },
  { ticker: "IATA", name: "MNC ENERGY INVESTMENTS Tbk" },
  { ticker: "IBFN", name: "INTAN BARU PRANA Tbk" },
  { ticker: "IBOS", name: "INDO BOGA SUKSES Tbk" },
  { ticker: "IBST", name: "INTI BANGUN SEJAHTERA Tbk" },
  { ticker: "ICBP", name: "INDOFOOD CBP SUKSES MAKMUR Tbk" },
  { ticker: "ICON", name: "ISLAND CONCEPTS INDONESIA Tbk" },
  { ticker: "IDEA", name: "IDEA INDONESIA AKADEMI Tbk" },
  { ticker: "IDPR", name: "INDONESIA PONDASI RAYA Tbk" },
  { ticker: "IFII", name: "INDONESIA FIBREBOARD INDUSTRY Tbk" },
  { ticker: "IFSH", name: "IFISHDECO Tbk" },
  { ticker: "IGAR", name: "CHAMPION PACIFIC INDONESIA Tbk" },
  { ticker: "IIKP", name: "INTI AGRI RESOURCES Tbk" },
  { ticker: "IKAI", name: "INTIKERAMIK ALAMASRI INDUSTRI Tbk" },
  { ticker: "IKAN", name: "ERA MANDIRI CEMERLANG Tbk" },
  { ticker: "IKBI", name: "SUMI INDO KABEL Tbk" },
  { ticker: "IKPM", name: "IKAPHARMINDO PUTRAMAS Tbk" },
  { ticker: "IMAS", name: "INDOMOBIL SUKSES INTERNASIONAL Tbk" },
  { ticker: "IMJS", name: "INDOMOBIL MULTI JASA Tbk" },
  { ticker: "IMPC", name: "IMPACK PRATAMA INDUSTRI Tbk" },
  { ticker: "INAF", name: "INDOFARMA Tbk" },
  { ticker: "INAI", name: "INDAL ALUMINIUM INDUSTRY Tbk" },
  { ticker: "INCF", name: "INDO KOMODITI KORPORA Tbk" },
  { ticker: "INCI", name: "INTANWIJAYA INTERNASIONAL Tbk" },
  { ticker: "INCO", name: "VALE INDONESIA Tbk" },
  { ticker: "INDF", name: "INDOFOOD SUKSES MAKMUR Tbk" },
  { ticker: "INDO", name: "ROYALINDO INVESTA WIJAYA Tbk" },
  { ticker: "INDR", name: "INDO-RAMA SYNTHETICS Tbk" },
  { ticker: "INDS", name: "INDOSPRING Tbk" },
  { ticker: "INDX", name: "TANAH LAUT Tbk" },
  { ticker: "INDY", name: "INDIKA ENERGY Tbk" },
  { ticker: "INET", name: "SINERGI INTI ANDALAN PRIMA Tbk" },
  { ticker: "INKP", name: "INDAH KIAT PULP AND PAPER Tbk" },
  { ticker: "INOV", name: "INOCYCLE TECHNOLOGY GROUP Tbk" },
  { ticker: "INPC", name: "BANK ARTHA GRAHA INTERNASIONAL Tbk" },
  { ticker: "INPP", name: "INDONESIAN PARADISE PROPERTY Tbk" },
  { ticker: "INPS", name: "INDAH PRAKASA SENTOSA Tbk" },
  { ticker: "INRU", name: "TOBA PULP LESTARI Tbk" },
  { ticker: "INTA", name: "INTRACO PENTA Tbk" },
  { ticker: "INTD", name: "INTER DELTA Tbk" },
  { ticker: "INTP", name: "INDOCEMENT TUNGGAL PRAKARSA Tbk" },
  { ticker: "IOTF", name: "SUMBER SINERGI MAKMUR Tbk" },
  { ticker: "IPAC", name: "ERA GRAHAREALTY Tbk" },
  { ticker: "IPCC", name: "INDONESIA KENDARAAN TERMINAL Tbk" },
  { ticker: "IPCM", name: "JASA ARMADA INDONESIA Tbk" },
  { ticker: "IPOL", name: "INDOPOLY SWAKARSA INDUSTRY Tbk" },
  { ticker: "IPPE", name: "INDO PURECO PRATAMA Tbk" },
  { ticker: "IPTV", name: "MNC VISION NETWORKS Tbk" },
  { ticker: "IRRA", name: "ITAMA RANORAYA Tbk" },
  { ticker: "IRSX", name: "FOLAGO GLOBAL NUSANTARA Tbk" },
  { ticker: "ISAP", name: "ISRA PRESISI INDONESIA Tbk" },
  { ticker: "ISAT", name: "INDOSAT Tbk" },
  { ticker: "ISEA", name: "INDO AMERICAN SEAFOODS Tbk" },
  { ticker: "ISSP", name: "STEEL PIPE INDUSTRY OF INDONESIA Tbk" },
  { ticker: "ITIC", name: "INDONESIAN TOBACCO Tbk" },
  { ticker: "ITMA", name: "SUMBER ENERGI ANDALAN Tbk" },
  { ticker: "ITMG", name: "INDO TAMBANGRAYA MEGAH Tbk" },
  { ticker: "JARR", name: "JHONLIN AGRO RAYA Tbk" },
  { ticker: "JAST", name: "JASNITA TELEKOMINDO Tbk" },
  { ticker: "JATI", name: "INFORMASI TEKNOLOGI INDONESIA Tbk" },
  { ticker: "JAWA", name: "JAYA AGRA WATTIE Tbk" },
  { ticker: "JAYA", name: "ARMADA BERJAYA TRANS Tbk" },
  { ticker: "JECC", name: "JEMBO CABLE COMPANY Tbk" },
  { ticker: "JGLE", name: "GRAHA ANDRASENTRA PROPERTINDO Tbk" },
  { ticker: "JIHD", name: "JAKARTA INTERNATIONAL HOTELS & DEVELOPMENT Tbk" },
  { ticker: "JKON", name: "JAYA KONSTRUKSI MANGGALA PRATAMA Tbk" },
  { ticker: "JMAS", name: "ASURANSI JIWA SYARIAH JASA MITRA ABADI Tbk" },
  { ticker: "JPFA", name: "JAPFA COMFEED INDONESIA Tbk" },
  { ticker: "JRPT", name: "JAYA REAL PROPERTY Tbk" },
  { ticker: "JSKY", name: "SKY ENERGY INDONESIA Tbk" },
  { ticker: "JSMR", name: "JASA MARGA (PERSERO) Tbk" },
  { ticker: "JSPT", name: "JAKARTA SETIABUDI INTERNASIONAL Tbk" },
  { ticker: "JTPE", name: "JASUINDO TIGA PERKASA Tbk" },
  { ticker: "KAEF", name: "KIMIA FARMA Tbk" },
  { ticker: "KAQI", name: "JANTRA GRUPO INDONESIA Tbk" },
  { ticker: "KARW", name: "MERATUS JASA PRIMA Tbk" },
  { ticker: "KAYU", name: "DARMI BERSAUDARA Tbk" },
  { ticker: "KBAG", name: "KARYA BERSAMA ANUGERAH Tbk" },
  { ticker: "KBLI", name: "KMI Wire and Cable Tbk" },
  { ticker: "KBLM", name: "KABELINDO MURNI Tbk" },
  { ticker: "KBLV", name: "FIRST MEDIA Tbk" },
  { ticker: "KBRI", name: "KERTAS BASUKI RACHMAT INDONESIA Tbk" },
  { ticker: "KDSI", name: "KEDAWUNG SETIA INDUSTRIAL Tbk" },
  { ticker: "KDTN", name: "PURI SENTUL PERMAI Tbk" },
  { ticker: "KEEN", name: "KENCANA ENERGI LESTARI Tbk" },
  { ticker: "KEJU", name: "MULIA BOGA RAYA Tbk" },
  { ticker: "KETR", name: "KETROSDEN TRIASMITRA Tbk" },
  { ticker: "KIAS", name: "KERAMIKA INDONESIA ASSOSIASI Tbk" },
  { ticker: "KICI", name: "KEDAUNG INDAH CAN Tbk" },
  { ticker: "KIJA", name: "KAWASAN INDUSTRI JABABEKA Tbk" },
  { ticker: "KING", name: "HOFFMEN CLEANINDO Tbk" },
  { ticker: "KINO", name: "KINO INDONESIA Tbk" },
  { ticker: "KIOS", name: "KIOSON KOMERSIAL INDONESIA Tbk" },
  { ticker: "KJEN", name: "KRIDA JARINGAN NUSANTARA Tbk" },
  { ticker: "KKES", name: "KUSUMA KEMINDO SENTOSA Tbk" },
  { ticker: "KKGI", name: "RESOURCE ALAM INDONESIA Tbk" },
  { ticker: "KLAS", name: "PELAYARAN KURNIA LAUTAN SEMESTA Tbk" },
  { ticker: "KLBF", name: "KALBE FARMA Tbk" },
  { ticker: "KLIN", name: "KLINKO KARYA IMAJI Tbk" },
  { ticker: "KMDS", name: "KURNIAMITRA DUTA SENTOSA Tbk" },
  { ticker: "KMTR", name: "KIRANA MEGATARA Tbk" },
  { ticker: "KOBX", name: "KOBEXINDO TRACTORS Tbk" },
  { ticker: "KOCI", name: "KOKOH EXA NUSANTARA Tbk" },
  { ticker: "KOIN", name: "KOKOH INTI AREBAMA Tbk" },
  { ticker: "KOKA", name: "KOKA INDONESIA Tbk" },
  { ticker: "KONI", name: "PERDANA BANGUN PUSAKA Tbk" },
  { ticker: "KOPI", name: "MITRA ENERGI PERSADA Tbk" },
  { ticker: "KOTA", name: "DMS PROPERTINDO Tbk" },
  { ticker: "KPIG", name: "MNC TOURISM INDONESIA Tbk" },
  { ticker: "KRAS", name: "KRAKATAU STEEL Tbk" },
  { ticker: "KREN", name: "QUANTUM CLOVERA INVESTAMA Tbk" },
  { ticker: "KRYA", name: "BANGUN KARYA PERKASA JAYA Tbk" },
  { ticker: "KSIX", name: "KENTANIX SUPRA INTERNATIONAL Tbk" },
  { ticker: "KUAS", name: "ACE OLDFIELDS Tbk" },
  { ticker: "LABA", name: "GREEN POWER GROUP Tbk" },
  { ticker: "LABS", name: "UBC MEDICAL INDONESIA Tbk" },
  { ticker: "LAJU", name: "JASA BERDIKARI LOGISTICS Tbk" },
  { ticker: "LAND", name: "TRIMITRA PROPERTINDO Tbk" },
  { ticker: "LAPD", name: "LEYAND INTERNATIONAL Tbk" },
  { ticker: "LCGP", name: "EUREKA PRIMA JAKARTA Tbk" },
  { ticker: "LCKM", name: "LCK GLOBAL KEDATON Tbk" },
  { ticker: "LEAD", name: "LOGINDO SAMUDRAMAKMUR Tbk" },
  { ticker: "LFLO", name: "IMAGO MULIA PERSADA Tbk" },
  { ticker: "LIFE", name: "MSIG LIFE INSURANCE INDONESIA Tbk" },
  { ticker: "LINK", name: "LINK NET Tbk" },
  { ticker: "LION", name: "LION METAL WORKS Tbk" },
  { ticker: "LIVE", name: "HOMECO VICTORIA MAKMUR Tbk" },
  { ticker: "LMAS", name: "LIMAS INDONESIA MAKMUR Tbk" },
  { ticker: "LMAX", name: "LUPROMAX PELUMAS INDONESIA Tbk" },
  { ticker: "LMPI", name: "LANGGENG MAKMUR INDUSTRI Tbk" },
  { ticker: "LMSH", name: "LIONMESH PRIMA Tbk" },
  { ticker: "LOPI", name: "LOGISTICSPLUS INTERNATIONAL Tbk" },
  { ticker: "LPCK", name: "LIPPO CIKARANG Tbk" },
  { ticker: "LPGI", name: "LIPPO GENERAL INSURANCE Tbk" },
  { ticker: "LPIN", name: "MULTI PRIMA SEJAHTERA Tbk" },
  { ticker: "LPKR", name: "LIPPO KARAWACI Tbk" },
  { ticker: "LPLI", name: "STAR PACIFIC Tbk" },
  { ticker: "LPPF", name: "MDS RETAILING Tbk" },
  { ticker: "LPPS", name: "LENOX PASIFIK INVESTAMA Tbk" },
  { ticker: "LRNA", name: "EKA SARI LORENA TRANSPORT Tbk" },
  { ticker: "LSIP", name: "PP LONDON SUMATRA INDONESIA Tbk" },
  { ticker: "LTLS", name: "LAUTAN LUAS Tbk" },
  { ticker: "LUCK", name: "SENTRAL MITRA INFORMATIKA Tbk" },
  { ticker: "LUCY", name: "LIMA DUA LIMA TIGA Tbk" },
  { ticker: "MABA", name: "MARGA ABHINAYA ABADI Tbk" },
  { ticker: "MAGP", name: "MULTI AGRO GEMILANG PLANTATION Tbk" },
  { ticker: "MAHA", name: "MANDIRI HERINDO ADIPERKASA Tbk" },
  { ticker: "MAIN", name: "MALINDO FEEDMILL Tbk" },
  { ticker: "MANG", name: "MANGGUNG POLAHRAYA Tbk" },
  { ticker: "MAPA", name: "MAP AKTIF ADIPERKASA Tbk" },
  { ticker: "MAPB", name: "MAP BOGA ADIPERKASA Tbk" },
  { ticker: "MAPI", name: "MITRA ADIPERKASA Tbk" },
  { ticker: "MARI", name: "MAHAKA RADIO INTEGRA Tbk" },
  { ticker: "MARK", name: "MARK DYNAMICS INDONESIA Tbk" },
  { ticker: "MASB", name: "BANK MULTIARTA SENTOSA Tbk" },
  { ticker: "MAXI", name: "MAXINDO KARYA ANUGERAH Tbk" },
  { ticker: "MAYA", name: "BANK MAYAPADA INTERNASIONAL Tbk" },
  { ticker: "MBAP", name: "MITRABARA ADIPERDANA Tbk" },
  { ticker: "MBMA", name: "MERDEKA BATTERY MATERIALS Tbk" },
  { ticker: "MBSS", name: "MITRABAHTERA SEGARA SEJATI Tbk" },
  { ticker: "MBTO", name: "MARTINA BERTO Tbk" },
  { ticker: "MCAS", name: "M CASH INTEGRASI Tbk" },
  { ticker: "MCOL", name: "PRIMA ANDALAN MANDIRI Tbk" },
  { ticker: "MCOR", name: "BANK CHINA CONSTRUCTION BANK INDONESIA Tbk" },
  { ticker: "MDIA", name: "INTERMEDIA CAPITAL Tbk" },
  { ticker: "MDIY", name: "DAYA INTIGUNA YASA Tbk" },
  { ticker: "MDKA", name: "MERDEKA COPPER GOLD Tbk" },
  { ticker: "MDKI", name: "EMDEKI UTAMA Tbk" },
  { ticker: "MDLA", name: "MEDELA POTENTIA Tbk" },
  { ticker: "MDLN", name: "MODERNLAND REALTY Tbk" },
  { ticker: "MDRN", name: "MODERN INTERNASIONAL Tbk" },
  { ticker: "MEDC", name: "MEDCO ENERGI INTERNASIONAL Tbk" },
  { ticker: "MEDS", name: "HETZER MEDICAL INDONESIA Tbk" },
  { ticker: "MEGA", name: "BANK MEGA Tbk" },
  { ticker: "MEJA", name: "HARTA DJAYA KARYA Tbk" },
  { ticker: "MENN", name: "MENN TEKNOLOGI INDONESIA Tbk" },
  { ticker: "MERI", name: "MERRY RIANA EDUKASI Tbk" },
  { ticker: "MERK", name: "MERCK Tbk" },
  { ticker: "META", name: "NUSANTARA INFRASTRUCTURE Tbk" },
  { ticker: "MFMI", name: "MULTIFILING MITRA INDONESIA Tbk" },
  { ticker: "MGLV", name: "PANCA ANUGRAH WISESA Tbk" },
  { ticker: "MGNA", name: "MAGNA INVESTAMA MANDIRI Tbk" },
  { ticker: "MGRO", name: "MAHKOTA GROUP Tbk" },
  { ticker: "MHKI", name: "MULTI HANNA KREASINDO Tbk" },
  { ticker: "MICE", name: "MULTI INDOCITRA Tbk" },
  { ticker: "MIDI", name: "MIDI UTAMA INDONESIA Tbk" },
  { ticker: "MIKA", name: "MITRA KELUARGA KARYASEHAT Tbk" },
  { ticker: "MINA", name: "SANURHASTA MITRA Tbk" },
  { ticker: "MINE", name: "SINAR TERANG MANDIRI Tbk" },
  { ticker: "MIRA", name: "MITRA INTERNATIONAL RESOURCES Tbk" },
  { ticker: "MITI", name: "MITRA INVESTINDO Tbk" },
  { ticker: "MKAP", name: "MULTIKARYA ASIA PASIFIK RAYA Tbk" },
  { ticker: "MKNT", name: "MITRA KOMUNIKASI NUSANTARA Tbk" },
  { ticker: "MKPI", name: "METROPOLITAN KENTJANA Tbk" },
  { ticker: "MKTR", name: "MENTHOBI KARYATAMA RAYA Tbk" },
  { ticker: "MLBI", name: "MULTI BINTANG INDONESIA Tbk" },
  { ticker: "MLIA", name: "MULIA INDUSTRINDO Tbk" },
  { ticker: "MLPL", name: "MULTIPOLAR Tbk" },
  { ticker: "MLPT", name: "MULTIPOLAR TECHNOLOGY Tbk" },
  { ticker: "MMIX", name: "MULTI MEDIKA INTERNASIONAL Tbk" },
  { ticker: "MMLP", name: "MEGA MANUNGGAL PROPERTY Tbk" },
  { ticker: "MNCN", name: "MEDIA NUSANTARA CITRA Tbk" },
  { ticker: "MOLI", name: "MADUSARI MURNI INDAH Tbk" },
  { ticker: "MORA", name: "EKAMAS MORA REPUBLIK Tbk" },
  { ticker: "MPIX", name: "MITRA PEDAGANG INDONESIA Tbk" },
  { ticker: "MPMX", name: "MITRA PINASTHIKA MUSTIKA Tbk" },
  { ticker: "MPOW", name: "MEGAPOWER MAKMUR Tbk" },
  { ticker: "MPPA", name: "MATAHARI PUTRA PRIMA Tbk" },
  { ticker: "MPRO", name: "MAHA PROPERTI INDONESIA Tbk" },
  { ticker: "MPXL", name: "MPX LOGISTICS INTERNATIONAL Tbk" },
  { ticker: "MRAT", name: "MUSTIKA RATU Tbk" },
  { ticker: "MREI", name: "MASKAPAI REASURANSI INDONESIA Tbk" },
  { ticker: "MSIE", name: "MULTISARANA INTAN EDUKA Tbk" },
  { ticker: "MSIN", name: "MNC DIGITAL ENTERTAINMENT Tbk" },
  { ticker: "MSJA", name: "MULTI SPUNINDO JAYA Tbk" },
  { ticker: "MSTI", name: "MASTERSYSTEM INFOTAMA Tbk" },
  { ticker: "MTDL", name: "METRODATA ELECTRONICS Tbk" },
  { ticker: "MTEL", name: "DAYAMITRA TELEKOMUNIKASI Tbk" },
  { ticker: "MTFN", name: "CAPITALINC INVESTMENT Tbk" },
  { ticker: "MTLA", name: "METROPOLITAN LAND Tbk" },
  { ticker: "MTMH", name: "MURNI SADAR Tbk" },
  { ticker: "MTPS", name: "META EPSI Tbk" },
  { ticker: "MTRA", name: "MITRA PEMUDA Tbk" },
  { ticker: "MTSM", name: "METRO REALTY Tbk, PT" },
  { ticker: "MTWI", name: "MALACCA TRUST WUWUNGAN INSURANCE Tbk" },
  { ticker: "MUTU", name: "MUTUAGUNG LESTARI Tbk" },
  { ticker: "MYOH", name: "SAMINDO RESOURCES Tbk" },
  { ticker: "MYOR", name: "MAYORA INDAH Tbk" },
  { ticker: "MYTX", name: "ASIA PACIFIC INVESTAMA Tbk" },
  { ticker: "NAIK", name: "ADIWARNA ANUGERAH ABADI Tbk" },
  { ticker: "NANO", name: "NANOTECH INDONESIA GLOBAL Tbk" },
  { ticker: "NASA", name: "ANDALAN PERKASA ABADI  Tbk" },
  { ticker: "NASI", name: "WAHANA INTI MAKMUR Tbk" },
  { ticker: "NATO", name: "OLYMPUS STRATEGIC INDONESIA Tbk" },
  { ticker: "NAYZ", name: "HASSANA BOGA SEJAHTERA TBK" },
  { ticker: "NCKL", name: "TRIMEGAH BANGUN PERSADA Tbk" },
  { ticker: "NELY", name: "PELAYARAN NELLY DWI PUTRI Tbk" },
  { ticker: "NEST", name: "ESTA INDONESIA Tbk" },
  { ticker: "NETV", name: "MDTV MEDIA TECHNOLOGIES Tbk" },
  { ticker: "NFCX", name: "NFC INDONESIA Tbk" },
  { ticker: "NICE", name: "ADHI KARTIKO PRATAMA Tbk" },
  { ticker: "NICK", name: "CHARNIC CAPITAL Tbk" },
  { ticker: "NICL", name: "PAM MINERAL Tbk" },
  { ticker: "NIKL", name: "PELAT TIMAH NUSANTARA Tbk" },
  { ticker: "NINE", name: "TECHNO9 INDONESIA Tbk" },
  { ticker: "NIRO", name: "CITY RETAIL DEVELOPMENTS Tbk" },
  { ticker: "NISP", name: "BANK OCBC NISP Tbk" },
  { ticker: "NOBU", name: "BANK NATIONALNOBU Tbk" },
  { ticker: "NPGF", name: "NUSA PALAPA GEMILANG Tbk" },
  { ticker: "NRCA", name: "NUSA RAYA CIPTA Tbk" },
  { ticker: "NSSS", name: "NUSANTARA SAWIT SEJAHTERA Tbk" },
  { ticker: "NTBK", name: "NUSATAMA BERKAH Tbk" },
  { ticker: "NUSA", name: "SINERGI MEGAH INTERNUSA Tbk" },
  { ticker: "NZIA", name: "NUSANTARA ALMAZIA Tbk" },
  { ticker: "OASA", name: "MAHARAKSA BIRU ENERGI Tbk" },
  { ticker: "OBAT", name: "BRIGIT BIOFARMAKA TEKNOLOGI Tbk" },
  { ticker: "OBMD", name: "OBM DRILCHEM Tbk" },
  { ticker: "OCAP", name: "ONIX CAPITAL Tbk" },
  { ticker: "OILS", name: "INDO OIL PERKASA Tbk" },
  { ticker: "OKAS", name: "ANCORA INDONESIA RESOURCES Tbk" },
  { ticker: "OLIV", name: "OSCAR MITRA SUKSES SEJAHTERA Tbk" },
  { ticker: "OMED", name: "JAYAMAS MEDICA INDUSTRI Tbk" },
  { ticker: "OMRE", name: "INDONESIA PRIMA PROPERTY Tbk" },
  { ticker: "OPMS", name: "OPTIMA PRIMA METAL SINERGI Tbk" },
  { ticker: "PACK", name: "ABADI NUSANTARA HIJAU INVESTAMA Tbk" },
  { ticker: "PADA", name: "PERSONEL ALIH DAYA Tbk" },
  { ticker: "PADI", name: "MINNA PADI INVESTAMA SEKURITAS Tbk" },
  { ticker: "PALM", name: "PROVIDENT INVESTASI BERSAMA Tbk" },
  { ticker: "PAMG", name: "BIMA SAKTI PERTIWI Tbk" },
  { ticker: "PANI", name: "PANTAI INDAH KAPUK DUA Tbk" },
  { ticker: "PANR", name: "PANORAMA SENTRAWISATA Tbk" },
  { ticker: "PANS", name: "PANIN SEKURITAS Tbk" },
  { ticker: "PART", name: "CIPTA PERDANA LANCAR Tbk" },
  { ticker: "PBID", name: "PANCA BUDI IDAMAN Tbk" },
  { ticker: "PBRX", name: "PAN BROTHERS Tbk" },
  { ticker: "PBSA", name: "PARAMITA BANGUN SARANA Tbk" },
  { ticker: "PCAR", name: "PRIMA CAKRAWALA ABADI Tbk" },
  { ticker: "PDES", name: "DESTINASI TIRTA NUSANTARA Tbk" },
  { ticker: "PDPP", name: "PRIMADAYA PLASTISINDO Tbk" },
  { ticker: "PEGE", name: "PANCA GLOBAL KAPITAL Tbk" },
  { ticker: "PEHA", name: "PHAPROS Tbk" },
  { ticker: "PEVE", name: "PENTA VALENT Tbk" },
  { ticker: "PGAS", name: "PERUSAHAAN GAS NEGARA (PERSERO) Tbk" },
  { ticker: "PGEO", name: "PERTAMINA GEOTHERMAL ENERGY Tbk" },
  { ticker: "PGJO", name: "BAHTERA BUMI RAYA Tbk" },
  { ticker: "PGLI", name: "PEMBANGUNAN GRAHA LESTARI INDAH Tbk" },
  { ticker: "PGUN", name: "PRADIKSI GUNATAMA Tbk" },
  { ticker: "PICO", name: "PELANGI INDAH CANINDO Tbk" },
  { ticker: "PIPA", name: "MULTI MAKMUR LEMINDO Tbk" },
  { ticker: "PJAA", name: "PEMBANGUNAN JAYA ANCOL Tbk" },
  { ticker: "PJHB", name: "PELAYARAN JAYA HIDUP BARU Tbk" },
  { ticker: "PKPK", name: "PARAGON KARYA PERKASA Tbk" },
  { ticker: "PLAN", name: "PLANET PROPERINDO JAYA Tbk" },
  { ticker: "PLAS", name: "POLARIS INVESTAMA TBK" },
  { ticker: "PLIN", name: "PLAZA INDONESIA REALTY Tbk" },
  { ticker: "PMJS", name: "PUTRA MANDIRI JEMBAR Tbk" },
  { ticker: "PMMP", name: "PANCA MITRA MULTIPERDANA Tbk" },
  { ticker: "PMUI", name: "PRIMA MULTI USAHA INDONESIA Tbk" },
  { ticker: "PNBN", name: "BANK PAN INDONESIA Tbk" },
  { ticker: "PNBS", name: "BANK PANIN DUBAI SYARIAH Tbk" },
  { ticker: "PNGO", name: "PINAGO UTAMA Tbk" },
  { ticker: "PNIN", name: "PANINVEST Tbk" },
  { ticker: "PNLF", name: "PANIN FINANCIAL Tbk" },
  { ticker: "PNSE", name: "PUDJIADI AND SONS Tbk" },
  { ticker: "POLA", name: "POOL ADVISTA FINANCE Tbk" },
  { ticker: "POLI", name: "POLLUX HOTELS GROUP Tbk" },
  { ticker: "POLL", name: "POLLUX PROPERTIES INDONESIA Tbk" },
  { ticker: "POLU", name: "GOLDEN FLOWER Tbk" },
  { ticker: "POLY", name: "ASIA PACIFIC FIBERS Tbk" },
  { ticker: "POOL", name: "POOL ADVISTA INDONESIA Tbk" },
  { ticker: "PORT", name: "NUSANTARA PELABUHAN HANDAL Tbk" },
  { ticker: "POSA", name: "BLISS PROPERTI INDONESIA Tbk" },
  { ticker: "POWR", name: "CIKARANG LISTRINDO Tbk" },
  { ticker: "PPGL", name: "PRIMA GLOBALINDO LOGISTIK Tbk" },
  { ticker: "PPRE", name: "PP PRESISI Tbk" },
  { ticker: "PPRI", name: "PAPEROCKS INDONESIA Tbk" },
  { ticker: "PPRO", name: "PP Properti Tbk" },
  { ticker: "PRAY", name: "FAMON AWAL BROS SEDAYA Tbk" },
  { ticker: "PRDA", name: "PRODIA WIDYAHUSADA Tbk" },
  { ticker: "PRIM", name: "ROYAL PRIMA Tbk" },
  { ticker: "PSAB", name: "J RESOURCES ASIA PASIFIK Tbk" },
  { ticker: "PSAT", name: "PANCARAN SAMUDERA TRANSPORT Tbk" },
  { ticker: "PSDN", name: "PRASIDHA ANEKA NIAGA Tbk" },
  { ticker: "PSGO", name: "PALMA SERASIH Tbk" },
  { ticker: "PSKT", name: "RED PLANET INDONESIA Tbk" },
  { ticker: "PSSI", name: "IMC PELITA LOGISTIK Tbk" },
  { ticker: "PTBA", name: "BUKIT ASAM (PERSERO) Tbk" },
  { ticker: "PTDU", name: "DJASA UBERSAKTI Tbk" },
  { ticker: "PTIS", name: "INDO STRAITS Tbk" },
  { ticker: "PTMP", name: "MITRA PACK Tbk" },
  { ticker: "PTMR", name: "MASTER PRINT Tbk" },
  { ticker: "PTPP", name: "PP (PERSERO) Tbk" },
  { ticker: "PTPS", name: "PULAU SUBUR Tbk" },
  { ticker: "PTPW", name: "PRATAMA WIDYA Tbk" },
  { ticker: "PTRO", name: "PETROSEA Tbk" },
  { ticker: "PTSN", name: "SAT NUSAPERSADA Tbk" },
  { ticker: "PTSP", name: "PIONEERINDO GOURMET INTERNATIONAL Tbk" },
  { ticker: "PUDP", name: "PUDJIADI PRESTIGE Tbk" },
  { ticker: "PURA", name: "PUTRA RAJAWALI KENCANA Tbk" },
  { ticker: "PURE", name: "TRINITAN METALS AND MINERALS Tbk" },
  { ticker: "PURI", name: "PURI GLOBAL SUKSES Tbk" },
  { ticker: "PWON", name: "PAKUWON JATI Tbk" },
  { ticker: "PYFA", name: "PYRIDAM FARMA Tbk" },
  { ticker: "PZZA", name: "SARIMELATI KENCANA Tbk" },
  { ticker: "RAAM", name: "TRIPAR MULTIVSION PLUS Tbk" },
  { ticker: "RAFI", name: "SARI KREASI BOGA Tbk" },
  { ticker: "RAJA", name: "RUKUN RAHARJA Tbk" },
  { ticker: "RALS", name: "RAMAYANA LESTARI SENTOSA Tbk" },
  { ticker: "RANC", name: "SUPRA BOGA LESTARI Tbk" },
  { ticker: "RATU", name: "RAHARJA ENERGI CEPU Tbk" },
  { ticker: "RBMS", name: "RISTIA BINTANG MAHKOTASEJATI Tbk" },
  { ticker: "RCCC", name: "UTAMA RADAR CAHAYA Tbk" },
  { ticker: "RDTX", name: "RODA VIVATEX Tbk" },
  { ticker: "REAL", name: "REPOWER ASIA INDONESIA Tbk" },
  { ticker: "RELF", name: "GRAHA MITRA ASIA Tbk" },
  { ticker: "RELI", name: "RELIANCE SEKURITAS INDONESIA Tbk" },
  { ticker: "RGAS", name: "KIAN SANTANG MULIATAMA Tbk" },
  { ticker: "RICY", name: "RICKY PUTRA GLOBALINDO Tbk" },
  { ticker: "RIGS", name: "RIG TENDERS INDONESIA Tbk" },
  { ticker: "RIMO", name: "RIMO INTERNATIONAL LESTARI Tbk" },
  { ticker: "RISE", name: "JAYA SUKSES MAKMUR SENTOSA Tbk" },
  { ticker: "RLCO", name: "ABADI LESTARI INDONESIA Tbk" },
  { ticker: "RMKE", name: "RMK ENERGY Tbk" },
  { ticker: "RMKO", name: "ROYALTAMA MULIA KONTRAKTORINDO Tbk" },
  { ticker: "ROCK", name: "ROCKFIELDS PROPERTI INDONESIA Tbk" },
  { ticker: "RODA", name: "PIKKO LAND DEVELOPMENT Tbk" },
  { ticker: "RONY", name: "ARACORD NUSANTARA GROUP Tbk" },
  { ticker: "ROTI", name: "NIPPON INDOSARI CORPINDO Tbk" },
  { ticker: "RSCH", name: "CHARLIE HOSPITAL SEMARANG Tbk" },
  { ticker: "RSGK", name: "KEDOYA ADYARAYA Tbk" },
  { ticker: "RUIS", name: "RADIANT UTAMA INTERINSCO Tbk" },
  { ticker: "RUNS", name: "GLOBAL SUKSES SOLUSI Tbk" },
  { ticker: "SAFE", name: "STEADY SAFE Tbk" },
  { ticker: "SAGE", name: "SAPTAUSAHA GEMILANGINDAH Tbk" },
  { ticker: "SAME", name: "SARANA MEDITAMA METROPOLITAN Tbk" },
  { ticker: "SAMF", name: "SARASWANTI ANUGERAH MAKMUR Tbk" },
  { ticker: "SAPX", name: "SATRIA ANTARAN PRIMA Tbk" },
  { ticker: "SATU", name: "KOTA SATU PROPERTI Tbk" },
  { ticker: "SBAT", name: "SEJAHTERA BINTANG ABADI TEXTILE Tbk" },
  { ticker: "SBMA", name: "SURYA BIRU MURNI ACETYLENE Tbk" },
  { ticker: "SCCO", name: "SUPREME CABLE MANUFACTURING & COMMERCE Tbk" },
  { ticker: "SCMA", name: "SURYA CITRA MEDIA Tbk" },
  { ticker: "SCNP", name: "SELARAS CITRA NUSANTARA PERKASA Tbk" },
  { ticker: "SCPI", name: "ORGANON PHARMA INDONESIA Tbk" },
  { ticker: "SDMU", name: "SIDOMULYO SELARAS Tbk" },
  { ticker: "SDPC", name: "MILLENNIUM PHARMACON INTERNATIONAL Tbk" },
  { ticker: "SDRA", name: "BANK WOORI SAUDARA INDONESIA 1906 Tbk" },
  { ticker: "SEMA", name: "SEMACOM INTEGRATED Tbk" },
  { ticker: "SFAN", name: "SURYA FAJAR CAPITAL Tbk" },
  { ticker: "SGER", name: "SUMBER GLOBAL ENERGY Tbk" },
  { ticker: "SGRO", name: "PRIME AGRI RESOURCES Tbk" },
  { ticker: "SHID", name: "HOTEL SAHID JAYA INTERNATIONAL Tbk" },
  { ticker: "SHIP", name: "SILLO MARITIME PERDANA Tbk" },
  { ticker: "SICO", name: "SIGMA ENERGY COMPRESSINDO Tbk" },
  { ticker: "SIDO", name: "INDUSTRI JAMU DAN FARMASI SIDO MUNCUL Tbk" },
  { ticker: "SILO", name: "SILOAM INTERNATIONAL HOSPITALS Tbk" },
  { ticker: "SIMA", name: "SIWANI MAKMUR Tbk" },
  { ticker: "SIMP", name: "SALIM IVOMAS PRATAMA Tbk" },
  { ticker: "SINI", name: "SINGARAJA PUTRA Tbk" },
  { ticker: "SIPD", name: "SREEYA SEWU INDONESIA Tbk" },
  { ticker: "SKBM", name: "SEKAR BUMI Tbk" },
  { ticker: "SKLT", name: "SEKAR LAUT Tbk" },
  { ticker: "SKRN", name: "SUPERKRANE MITRA UTAMA Tbk" },
  { ticker: "SKYB", name: "NORTHCLIFF CITRANUSA INDONESIA Tbk" },
  { ticker: "SLIS", name: "GAYA ABADI SEMPURNA Tbk" },
  { ticker: "SMAR", name: "SINAR MAS AGRO RESOURCES AND TECHNOLOGY Tbk" },
  { ticker: "SMBR", name: "SEMEN BATURAJA (PERSERO) Tbk" },
  { ticker: "SMCB", name: "SOLUSI BANGUN INDONESIA Tbk" },
  { ticker: "SMDM", name: "SURYAMAS DUTAMAKMUR Tbk" },
  { ticker: "SMDR", name: "SAMUDERA INDONESIA Tbk" },
  { ticker: "SMGA", name: "SUMBER MINERAL GLOBAL ABADI Tbk" },
  { ticker: "SMGR", name: "SEMEN INDONESIA (PERSERO) Tbk" },
  { ticker: "SMIL", name: "SARANA MITRA LUAS Tbk" },
  { ticker: "SMKL", name: "SATYAMITRA KEMAS LESTARI Tbk" },
  { ticker: "SMKM", name: "SUMBER MAS KONSTRUKSI Tbk" },
  { ticker: "SMLE", name: "SINERGI MULTI LESTARINDO Tbk" },
  { ticker: "SMMA", name: "SINAR MAS MULTIARTHA Tbk" },
  { ticker: "SMMT", name: "GOLDEN EAGLE ENERGY Tbk" },
  { ticker: "SMRA", name: "SUMMARECON AGUNG Tbk" },
  { ticker: "SMRU", name: "SMR UTAMA Tbk" },
  { ticker: "SMSM", name: "SELAMAT SEMPURNA Tbk" },
  { ticker: "SNLK", name: "SUNTER LAKESIDE HOTEL Tbk" },
  { ticker: "SOCI", name: "SOECHI LINES Tbk" },
  { ticker: "SOFA", name: "SOLUSI ENVIRONMENT ASIA Tbk" },
  { ticker: "SOHO", name: "SOHO GLOBAL HEALTH Tbk" },
  { ticker: "SOLA", name: "XOLARE RCR ENERGY Tbk" },
  { ticker: "SONA", name: "SONA TOPAS TOURISM INDUSTRY Tbk" },
  { ticker: "SOSS", name: "SHIELD ON SERVICE Tbk" },
  { ticker: "SOTS", name: "SATRIA MEGA KENCANA Tbk" },
  { ticker: "SOUL", name: "MITRA TIRTA BUWANA Tbk" },
  { ticker: "SPMA", name: "SUPARMA Tbk" },
  { ticker: "SPRE", name: "SORAYA BERJAYA INDONESIA Tbk" },
  { ticker: "SPTO", name: "SURYA PERTIWI Tbk" },
  { ticker: "SQMI", name: "WILTON MAKMUR INDONESIA Tbk" },
  { ticker: "SRAJ", name: "SEJAHTERARAYA ANUGRAHJAYA Tbk, PT" },
  { ticker: "SRIL", name: "SRI REJEKI ISMAN Tbk" },
  { ticker: "SRSN", name: "INDO ACIDATAMA Tbk" },
  { ticker: "SRTG", name: "SARATOGA INVESTAMA SEDAYA Tbk" },
  { ticker: "SSIA", name: "SURYA SEMESTA INTERNUSA Tbk" },
  { ticker: "SSMS", name: "SAWIT SUMBERMAS SARANA Tbk" },
  { ticker: "SSTM", name: "SUNSON TEXTILE MANUFACTURER Tbk" },
  { ticker: "STAA", name: "SUMBER TANI AGUNG RESOURCES Tbk" },
  { ticker: "STAR", name: "BUANA ARTHA ANUGERAH Tbk" },
  { ticker: "STRK", name: "LOVINA BEACH BREWERY Tbk" },
  { ticker: "STTP", name: "SIANTAR TOP Tbk" },
  { ticker: "SUGI", name: "SUGIH ENERGY Tbk, PT" },
  { ticker: "SULI", name: "SLJ GLOBAL Tbk" },
  { ticker: "SUNI", name: "SUNINDO PRATAMA Tbk" },
  { ticker: "SUPA", name: "SUPER BANK INDONESIA Tbk" },
  { ticker: "SUPR", name: "SOLUSI TUNAS PRATAMA Tbk" },
  { ticker: "SURE", name: "SUPER ENERGY Tbk" },
  { ticker: "SURI", name: "MAJA AGUNG LATEXINDO Tbk" },
  { ticker: "SWAT", name: "SRIWAHANA ADITYAKARTA Tbk" },
  { ticker: "SWID", name: "SARASWANTI INDOLAND DEVELOPMENT Tbk" },
  { ticker: "TALF", name: "TUNAS ALFIN Tbk" },
  { ticker: "TAMA", name: "LANCARTAMA SEJATI Tbk" },
  { ticker: "TAMU", name: "PELAYARAN TAMARIN SAMUDRA Tbk" },
  { ticker: "TAPG", name: "TRIPUTRA AGRO PERSADA Tbk" },
  { ticker: "TARA", name: "AGUNG SEMESTA SEJAHTERA Tbk" },
  { ticker: "TAXI", name: "EXPRESS TRANSINDO UTAMA Tbk" },
  { ticker: "TAYS", name: "JAYA SWARASA AGUNG Tbk" },
  { ticker: "TBIG", name: "TOWER BERSAMA INFRASTRUCTURE Tbk" },
  { ticker: "TBLA", name: "TUNAS BARU LAMPUNG Tbk" },
  { ticker: "TBMS", name: "TEMBAGA MULIA SEMANAN Tbk" },
  { ticker: "TCID", name: "MANDOM INDONESIA Tbk" },
  { ticker: "TCPI", name: "TRANSCOAL PACIFIC Tbk" },
  { ticker: "TDPM", name: "TRIDOMAIN PERFORMANCE MATERIALS Tbk" },
  { ticker: "TEBE", name: "DANA BRATA LUHUR Tbk" },
  { ticker: "TECH", name: "INDOSTERLING TECHNOMEDIA Tbk" },
  { ticker: "TELE", name: "OMNI INOVASI INDONESIA Tbk" },
  { ticker: "TFAS", name: "TELEFAST INDONESIA Tbk" },
  { ticker: "TFCO", name: "TIFICO FIBER INDONESIA Tbk" },
  { ticker: "TGKA", name: "TIGARAKSA SATRIA Tbk" },
  { ticker: "TGRA", name: "TERREGRA ASIA ENERGY Tbk" },
  { ticker: "TGUK", name: "PLATINUM WAHAB NUSANTARA Tbk" },
  { ticker: "TIFA", name: "KDB TIFA FINANCE Tbk" },
  { ticker: "TINS", name: "TIMAH Tbk" },
  { ticker: "TIRA", name: "TIRA AUSTENITE Tbk" },
  { ticker: "TIRT", name: "TIRTA MAHAKAM RESOURCES Tbk" },
  { ticker: "TKIM", name: "PABRIK KERTAS TJIWI KIMIA Tbk" },
  { ticker: "TLDN", name: "TELADAN PRIMA AGRO Tbk" },
  { ticker: "TLKM", name: "TELKOM INDONESIA (PERSERO) Tbk" },
  { ticker: "TMAS", name: "TEMAS Tbk" },
  { ticker: "TMPO", name: "TEMPO INTI MEDIA Tbk" },
  { ticker: "TNCA", name: "TRIMUDA NUANSA CITRA Tbk" },
  { ticker: "TOBA", name: "TBS ENERGI UTAMA Tbk" },
  { ticker: "TOOL", name: "ROHARTINDO NUSANTARA LUAS Tbk" },
  { ticker: "TOPS", name: "TOTALINDO EKA PERSADA Tbk" },
  { ticker: "TOSK", name: "TOPINDO SOLUSI KOMUNIKA Tbk" },
  { ticker: "TOTL", name: "TOTAL BANGUN PERSADA Tbk" },
  { ticker: "TOTO", name: "SURYA TOTO INDONESIA Tbk" },
  { ticker: "TOWR", name: "SARANA MENARA NUSANTARA Tbk" },
  { ticker: "TOYS", name: "SUNINDO ADIPERSADA Tbk" },
  { ticker: "TPIA", name: "CHANDRA ASRI PACIFIC Tbk" },
  { ticker: "TPMA", name: "TRANS POWER MARINE Tbk" },
  { ticker: "TRAM", name: "TRADA ALAM MINERA Tbk" },
  { ticker: "TRGU", name: "CERESTAR INDONESIA Tbk" },
  { ticker: "TRIL", name: "TRIWIRA INSANLESTARI Tbk" },
  { ticker: "TRIM", name: "TRIMEGAH SEKURITAS INDONESIA Tbk" },
  { ticker: "TRIN", name: "PERINTIS TRINITI PROPERTI Tbk" },
  { ticker: "TRIO", name: "TRIKOMSEL OKE Tbk" },
  { ticker: "TRIS", name: "TRISULA INTERNATIONAL Tbk" },
  { ticker: "TRJA", name: "TRANSKON JAYA Tbk" },
  { ticker: "TRON", name: "TEKNOLOGI KARYA DIGITAL NUSA Tbk" },
  { ticker: "TRST", name: "TRIAS SENTOSA Tbk" },
  { ticker: "TRUE", name: "TRINITI DINAMIK Tbk" },
  { ticker: "TRUK", name: "GUNA TIMUR RAYA Tbk" },
  { ticker: "TRUS", name: "TRUST FINANCE INDONESIA Tbk" },
  { ticker: "TSPC", name: "TEMPO SCAN PACIFIC Tbk" },
  { ticker: "TUGU", name: "ASURANSI TUGU PRATAMA INDONESIA Tbk" },
  { ticker: "TYRE", name: "KING TIRE INDONESIA Tbk" },
  { ticker: "UANG", name: "PAKUAN Tbk" },
  { ticker: "UCID", name: "UNI-CHARM INDONESIA Tbk" },
  { ticker: "UDNG", name: "AGRO BAHARI NUSANTARA Tbk" },
  { ticker: "UFOE", name: "DAMAI SEJAHTERA ABADI Tbk" },
  { ticker: "ULTJ", name: "ULTRAJAYA MILK INDUSTRY AND TRADING COMPANY Tbk" },
  { ticker: "UNIC", name: "UNGGUL INDAH CAHAYA Tbk" },
  { ticker: "UNIQ", name: "ULIMA NITRA Tbk" },
  { ticker: "UNIT", name: "CAHAYA PERMATA SEJAHTERA Tbk" },
  { ticker: "UNSP", name: "BAKRIE SUMATERA PLANTATIONS Tbk" },
  { ticker: "UNTD", name: "TERANG DUNIA INTERNUSA Tbk" },
  { ticker: "UNTR", name: "UNITED TRACTORS Tbk" },
  { ticker: "UNVR", name: "UNILEVER INDONESIA Tbk" },
  { ticker: "URBN", name: "URBAN JAKARTA PROPERTINDO Tbk" },
  { ticker: "UVCR", name: "TRIMEGAH KARYA PRATAMA Tbk" },
  { ticker: "VAST", name: "VASTLAND INDONESIA Tbk" },
  { ticker: "VERN", name: "VERONA INDAH PICTURES Tbk" },
  { ticker: "VICI", name: "VICTORIA CARE INDONESIA Tbk" },
  { ticker: "VICO", name: "VICTORIA INVESTAMA Tbk" },
  { ticker: "VINS", name: "VICTORIA INSURANCE Tbk" },
  { ticker: "VISI", name: "SATU VISI PUTRA Tbk" },
  { ticker: "VIVA", name: "VISI MEDIA ASIA Tbk" },
  { ticker: "VKTR", name: "VKTR TEKNOLOGI MOBILITAS Tbk" },
  { ticker: "VOKS", name: "VOKSEL ELECTRIC Tbk" },
  { ticker: "VRNA", name: "MIZUHO LEASING INDONESIA Tbk" },
  { ticker: "VTNY", name: "VENTENY FORTUNA INTERNATIONAL Tbk" },
  { ticker: "WAPO", name: "WAHANA PRONATURAL Tbk" },
  { ticker: "WBSA", name: "BSA LOGISTICS INDONESIA Tbk" },
  { ticker: "WEGE", name: "WIJAYA KARYA BANGUNAN GEDUNG Tbk" },
  { ticker: "WEHA", name: "WEHA TRANSPORTASI INDONESIA Tbk" },
  { ticker: "WGSH", name: "WIRA GLOBAL SOLUSI Tbk" },
  { ticker: "WICO", name: "WICAKSANA OVERSEAS INTERNATIONAL Tbk" },
  { ticker: "WIDI", name: "WIDIANT JAYA KRENINDO Tbk" },
  { ticker: "WIFI", name: "SOLUSI SINERGI DIGITAL Tbk" },
  { ticker: "WIIM", name: "WISMILAK INTI MAKMUR Tbk" },
  { ticker: "WIKA", name: "WIJAYA KARYA (PERSERO) Tbk" },
  { ticker: "WINE", name: "HATTEN BALI Tbk" },
  { ticker: "WINR", name: "WINNER NUSANTARA JAYA Tbk" },
  { ticker: "WINS", name: "WINTERMAR OFFSHORE MARINE Tbk" },
  { ticker: "WIRG", name: "WIR ASIA Tbk" },
  { ticker: "WMPP", name: "WIDODO MAKMUR PERKASA Tbk" },
  { ticker: "WMUU", name: "WIDODO MAKMUR UNGGAS Tbk" },
  { ticker: "WOMF", name: "WAHANA OTTOMITRA MULTIARTHA Tbk" },
  { ticker: "WOOD", name: "INTEGRA INDOCABINET Tbk" },
  { ticker: "WOWS", name: "GINTING JAYA ENERGI Tbk" },
  { ticker: "WSBP", name: "WASKITA BETON PRECAST Tbk" },
  { ticker: "WSKT", name: "WASKITA KARYA (PERSERO) Tbk" },
  { ticker: "WTON", name: "WIJAYA KARYA BETON Tbk" },
  { ticker: "YELO", name: "YELOOO INTEGRA DATANET Tbk" },
  { ticker: "YOII", name: "ASURANSI DIGITAL BERSAMA Tbk" },
  { ticker: "YPAS", name: "YANAPRIMA HASTAPERSADA Tbk" },
  { ticker: "YULE", name: "YULIE SEKURITAS INDONESIA Tbk" },
  { ticker: "YUPI", name: "YUPI INDO JELLY GUM Tbk" },
  { ticker: "ZATA", name: "BERSAMA ZATTA JAYA Tbk" },
  { ticker: "ZBRA", name: "DOSNI ROHA INDONESIA Tbk" },
  { ticker: "ZINC", name: "KAPUAS PRIMA COAL Tbk" },
  { ticker: "ZONE", name: "MEGA PERINTIS Tbk" },
  { ticker: "ZYRX", name: "ZYREXINDO MANDIRI BUANA Tbk" },
] as const;
