begin;

create table if not exists public.ownership_classification_snapshots (
  id bigint generated by default as identity primary key,
  ticker text not null references public.stocks(ticker) on update cascade on delete cascade,
  issuer_name text not null,
  report_date date not null,
  total_scripless bigint not null check (total_scripless > 0),
  holdings jsonb not null default '{}'::jsonb check (jsonb_typeof(holdings) = 'object'),
  source_file text not null,
  created_at timestamptz not null default now(),
  unique (ticker, report_date)
);

create index if not exists ownership_classification_date_idx
  on public.ownership_classification_snapshots(report_date desc, ticker);

create table if not exists public.ownership_classification_imports (
  report_date date primary key,
  source_file text not null,
  issuer_count integer not null check (issuer_count > 0),
  imported_at timestamptz not null default now()
);

alter table public.ownership_classification_snapshots enable row level security;

drop policy if exists "ownership classifications are readable" on public.ownership_classification_snapshots;
create policy "ownership classifications are readable"
  on public.ownership_classification_snapshots for select using (true);

alter table public.ownership_classification_imports enable row level security;

drop policy if exists "ownership classification imports are readable" on public.ownership_classification_imports;
create policy "ownership classification imports are readable"
  on public.ownership_classification_imports for select using (true);

create or replace function public.replace_ownership_classification(
  p_report_date date,
  p_rows jsonb,
  p_source_file text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row_count integer;
begin
  if p_report_date is null or coalesce(jsonb_typeof(p_rows), '') <> 'array' or nullif(btrim(p_source_file), '') is null then
    raise exception 'Metadata snapshot klasifikasi tidak valid.';
  end if;
  v_row_count := jsonb_array_length(p_rows);
  if v_row_count < 1 or v_row_count > 2000 then
    raise exception 'Jumlah emiten harus antara 1 dan 2000.';
  end if;

  insert into public.stocks (ticker, name, updated_at)
  select upper(btrim(item.ticker)), max(btrim(item.issuer_name)), now()
  from jsonb_to_recordset(p_rows) as item(ticker text, issuer_name text)
  group by upper(btrim(item.ticker))
  on conflict (ticker) do update set name = excluded.name, updated_at = now();

  delete from public.ownership_classification_snapshots where report_date = p_report_date;
  insert into public.ownership_classification_snapshots (
    ticker, issuer_name, report_date, total_scripless, holdings, source_file
  )
  select
    upper(btrim(item.ticker)), btrim(item.issuer_name), p_report_date,
    item.total_scripless, item.holdings, left(btrim(p_source_file), 255)
  from jsonb_to_recordset(p_rows) as item(
    ticker text, issuer_name text, report_date date, total_scripless bigint, holdings jsonb
  )
  where item.report_date = p_report_date
    and item.total_scripless > 0
    and jsonb_typeof(item.holdings) = 'object';

  if (select count(*) from public.ownership_classification_snapshots where report_date = p_report_date) <> v_row_count then
    raise exception 'Sebagian baris klasifikasi tidak valid.';
  end if;

  insert into public.ownership_classification_imports (report_date, source_file, issuer_count, imported_at)
  values (p_report_date, left(btrim(p_source_file), 255), v_row_count, now())
  on conflict (report_date) do update set
    source_file = excluded.source_file,
    issuer_count = excluded.issuer_count,
    imported_at = excluded.imported_at;

  return jsonb_build_object('importedCount', v_row_count, 'reportDate', p_report_date);
end;
$$;

revoke all on function public.replace_ownership_classification(date, jsonb, text) from public, anon, authenticated;
grant execute on function public.replace_ownership_classification(date, jsonb, text) to service_role;

commit;
