begin;

create table if not exists public.financial_reports (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  ticker text not null,
  entity_name text not null,
  industry_family text not null default '',
  sector text not null default '',
  subsector text not null default '',
  taxonomy_family text not null default 'unknown' check (taxonomy_family in ('general', 'financial', 'unknown')),
  period_label text not null default '',
  period_start date not null,
  period_end date not null,
  prior_period_start date,
  prior_period_end date,
  currency text not null,
  unit_label text not null default '',
  unit_multiplier numeric not null default 1 check (unit_multiplier > 0),
  report_type text not null default '',
  auditor text not null default '',
  source_file text not null,
  storage_path text,
  headline text not null,
  executive_summary text not null,
  kpis jsonb not null default '{}'::jsonb,
  insights jsonb not null default '[]'::jsonb,
  breakdowns jsonb not null default '[]'::jsonb,
  analyst_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, ticker, period_end)
);

create table if not exists public.financial_report_facts (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.financial_reports(id) on delete cascade,
  statement text not null check (statement in ('profile', 'balance_sheet', 'income_statement', 'cash_flow', 'note')),
  sheet_code text not null,
  sheet_title text not null default '',
  row_number integer not null check (row_number > 0),
  label text not null,
  label_en text not null default '',
  concept text,
  current_value numeric,
  prior_value numeric,
  created_at timestamptz not null default now()
);

create index if not exists financial_reports_owner_period_idx
  on public.financial_reports(owner_id, period_end desc, ticker);
create index if not exists financial_report_facts_report_statement_idx
  on public.financial_report_facts(report_id, statement, row_number);
create index if not exists financial_report_facts_report_concept_idx
  on public.financial_report_facts(report_id, concept) where concept is not null;

drop trigger if exists financial_reports_set_updated_at on public.financial_reports;
create trigger financial_reports_set_updated_at
before update on public.financial_reports
for each row execute function public.set_updated_at();

alter table public.financial_reports enable row level security;
alter table public.financial_report_facts enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'financial-reports',
  'financial-reports',
  false,
  10485760,
  array['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.replace_admin_financial_report(
  p_report jsonb,
  p_facts jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_owner constant uuid := '00000000-0000-4000-8000-000000000001';
  v_report_id uuid;
begin
  if jsonb_typeof(coalesce(p_facts, '[]'::jsonb)) <> 'array' then
    raise exception 'Financial report facts must be an array';
  end if;

  insert into public.financial_reports (
    owner_id, ticker, entity_name, industry_family, sector, subsector, taxonomy_family,
    period_label, period_start, period_end, prior_period_start, prior_period_end,
    currency, unit_label, unit_multiplier, report_type, auditor, source_file, storage_path,
    headline, executive_summary, kpis, insights, breakdowns
  ) values (
    admin_owner,
    upper(p_report->>'ticker'),
    p_report->>'entity_name',
    coalesce(p_report->>'industry_family', ''),
    coalesce(p_report->>'sector', ''),
    coalesce(p_report->>'subsector', ''),
    coalesce(p_report->>'taxonomy_family', 'unknown'),
    coalesce(p_report->>'period_label', ''),
    (p_report->>'period_start')::date,
    (p_report->>'period_end')::date,
    nullif(p_report->>'prior_period_start', '')::date,
    nullif(p_report->>'prior_period_end', '')::date,
    p_report->>'currency',
    coalesce(p_report->>'unit_label', ''),
    (p_report->>'unit_multiplier')::numeric,
    coalesce(p_report->>'report_type', ''),
    coalesce(p_report->>'auditor', ''),
    p_report->>'source_file',
    nullif(p_report->>'storage_path', ''),
    p_report->>'headline',
    p_report->>'executive_summary',
    coalesce(p_report->'kpis', '{}'::jsonb),
    coalesce(p_report->'insights', '[]'::jsonb),
    coalesce(p_report->'breakdowns', '[]'::jsonb)
  )
  on conflict (owner_id, ticker, period_end) do update set
    entity_name = excluded.entity_name,
    industry_family = excluded.industry_family,
    sector = excluded.sector,
    subsector = excluded.subsector,
    taxonomy_family = excluded.taxonomy_family,
    period_label = excluded.period_label,
    period_start = excluded.period_start,
    prior_period_start = excluded.prior_period_start,
    prior_period_end = excluded.prior_period_end,
    currency = excluded.currency,
    unit_label = excluded.unit_label,
    unit_multiplier = excluded.unit_multiplier,
    report_type = excluded.report_type,
    auditor = excluded.auditor,
    source_file = excluded.source_file,
    storage_path = excluded.storage_path,
    headline = excluded.headline,
    executive_summary = excluded.executive_summary,
    kpis = excluded.kpis,
    insights = excluded.insights,
    breakdowns = excluded.breakdowns,
    updated_at = now()
  returning id into v_report_id;

  delete from public.financial_report_facts where financial_report_facts.report_id = v_report_id;

  insert into public.financial_report_facts (
    report_id, statement, sheet_code, sheet_title, row_number,
    label, label_en, concept, current_value, prior_value
  )
  select
    v_report_id,
    row.statement,
    row.sheet_code,
    coalesce(row.sheet_title, ''),
    row.row_number,
    row.label,
    coalesce(row.label_en, ''),
    nullif(row.concept, ''),
    row.current_value,
    row.prior_value
  from jsonb_to_recordset(coalesce(p_facts, '[]'::jsonb)) as row(
    statement text,
    sheet_code text,
    sheet_title text,
    row_number integer,
    label text,
    label_en text,
    concept text,
    current_value numeric,
    prior_value numeric
  );

  return v_report_id;
end;
$$;

revoke all on function public.replace_admin_financial_report(jsonb, jsonb) from public;
revoke all on function public.replace_admin_financial_report(jsonb, jsonb) from anon;
revoke all on function public.replace_admin_financial_report(jsonb, jsonb) from authenticated;
grant execute on function public.replace_admin_financial_report(jsonb, jsonb) to service_role;

commit;
