"use client";

import { useMemo } from "react";
import { AlertTriangle, FlaskConical, ShoppingCart } from "lucide-react";
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { calculateHmetdBuyer, hmetdBuyerPriceRows, hmetdBuyerStatusLabels } from "@/lib/calculations/hmetd-buyer";
import { formatCurrency, formatNumber, formatPercentage, formatSimulationInput, parseSimulationNumber } from "@/lib/calculations/right-issue-format";
import type { HmetdBuyerDraft, HmetdBuyerInput } from "@/types/hmetd-buyer";
import type { RightIssueDraft } from "@/types/right-issue";

type Props = { terms: RightIssueDraft; draft: HmetdBuyerDraft; example: "LAPD" | "BUVA" | null; nonStandardRight: boolean; onChange: (key: keyof HmetdBuyerDraft, value: string) => void; onTermsChange: (key: keyof RightIssueDraft, value: string) => void; onExample: (ticker: "LAPD" | "BUVA") => void };
const tones = { cheap: "text-emerald-700", thin: "text-amber-700", equal: "text-gray-700", expensive: "text-red-600" };

export function HmetdBuyer({ terms, draft, example, nonStandardRight, onChange, onTermsChange, onExample }: Props) {
  const input: HmetdBuyerInput = useMemo(() => ({
    rightsQuantity: parseSimulationNumber(draft.rightsQuantity), rightsPrice: parseSimulationNumber(terms.marketRightsPrice), subscriptionPrice: parseSimulationNumber(terms.subscriptionPrice), referencePrice: parseSimulationNumber(draft.referencePrice), salePrice: draft.salePrice.trim() ? parseSimulationNumber(draft.salePrice) : null,
    bufferPercent: parseSimulationNumber(draft.bufferPercent), buyFeePercent: parseSimulationNumber(draft.buyFeePercent), sellFeePercent: parseSimulationNumber(draft.sellFeePercent), redemptionFee: parseSimulationNumber(draft.redemptionFee),
  }), [terms.marketRightsPrice, terms.subscriptionPrice, draft]);
  const result = useMemo(() => calculateHmetdBuyer(input), [input]);
  const missing = [draft.rightsQuantity, terms.marketRightsPrice, terms.subscriptionPrice, draft.referencePrice, draft.bufferPercent, draft.buyFeePercent, draft.sellFeePercent, draft.redemptionFee].some((value) => !value.trim());
  const calculation = missing || nonStandardRight ? null : result.data;
  const rows = calculation ? hmetdBuyerPriceRows(input) : [];
  const chartRows = calculation ? [...new Set([0, input.referencePrice * 0.6, input.referencePrice * 0.8, input.referencePrice, input.referencePrice * 1.2, input.referencePrice * 1.4, calculation.breakEvenStockPrice, calculation.salePrice])].sort((a, b) => a - b).flatMap((price) => { const outcome = calculateHmetdBuyer({ ...input, salePrice: price }).data; return outcome ? [{ price, profit: outcome.profitLoss }] : []; }) : [];

  function field(id: string, label: string, value: string, change: (value: string) => void, unit: string, integer = false, placeholder = "0") {
    return <label htmlFor={`buyer-${id}`} className="grid min-w-0 content-start gap-1.5 text-sm font-medium text-gray-700"><span>{label}</span><span className="flex h-11 min-w-0 items-center gap-2 rounded-md border border-gray-300 bg-white px-3 focus-within:border-red-500 focus-within:ring-2 focus-within:ring-red-100"><input id={`buyer-${id}`} inputMode={integer ? "numeric" : "decimal"} value={value} onChange={(event) => change(formatSimulationInput(event.target.value, integer))} autoComplete="off" placeholder={placeholder} className="w-full min-w-0 bg-transparent text-sm tabular-nums text-gray-950 outline-none" /><span className="shrink-0 text-xs text-gray-500">{unit}</span></span></label>;
  }
  function metric(label: string, value: string, tone = "text-gray-950") { return <div className="min-w-0 border-b border-gray-100 py-3"><dt className="text-xs text-gray-500">{label}</dt><dd className={`mt-1 break-words text-base font-semibold tabular-nums sm:text-lg ${tone}`}>{value}</dd></div>; }
  const cap = (value: number) => value < 0 ? "Tidak ada harga nonnegatif" : formatCurrency(value, 4);

  return <section aria-label="Analisis pembeli HMETD" className="min-w-0">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><ShoppingCart className="size-5 text-red-600" /><h2 className="text-lg font-semibold text-gray-950">Beli HMETD & Tebus</h2></div><div className="flex flex-wrap gap-2">{(["LAPD", "BUVA"] as const).map((ticker) => <button key={ticker} type="button" onClick={() => onExample(ticker)} className="inline-flex min-h-10 items-center gap-2 rounded-md border border-gray-300 px-3 text-sm font-medium text-gray-700 hover:bg-gray-50"><FlaskConical className="size-4" />Contoh {ticker}</button>)}</div></div>
    {example ? <p className="mb-4 border-l-2 border-amber-400 bg-amber-50 px-3 py-3 text-xs leading-5 text-amber-900">Contoh {example}: harga tebus {example === "LAPD" ? "Rp50 masih indikatif (dokumen 11 September 2026)" : "Rp250 mengacu dokumen 6 Oktober 2026"}. Harga beli HMETD, acuan saham, jumlah hak, dan buffer adalah asumsi latihan, bukan harga pasar terkini atau nilai wajar emiten.</p> : null}
    {nonStandardRight ? <p role="alert" className="mb-4 border-l-2 border-red-500 bg-red-50 p-3 text-sm leading-6 text-red-800">Dokumen menyebut konversi bukan 1 HMETD : 1 saham baru. Mode pembeli ini tidak mendukung konversi tersebut; perhitungan dinonaktifkan agar biaya per saham tidak keliru.</p> : null}
    <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)]">
      <div className="min-w-0 divide-y divide-gray-200 border-y border-gray-200">
        <div className="py-5"><h3 className="mb-4 text-base font-semibold text-gray-950">Pembelian Hak</h3><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="buyer-ticker" className="grid gap-1.5 text-sm font-medium text-gray-700">Ticker<input id="buyer-ticker" maxLength={4} value={terms.ticker} onChange={(event) => onTermsChange("ticker", event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""))} placeholder="Kode saham" className="h-11 w-full min-w-0 rounded-md border border-gray-300 px-3 text-sm" /></label>
          {field("rightsQuantity", "Jumlah HMETD", draft.rightsQuantity, (value) => onChange("rightsQuantity", value), "hak", true)}
          {field("rightsPrice", "Harga beli HMETD per hak", terms.marketRightsPrice, (value) => onTermsChange("marketRightsPrice", value), "Rp")}
          {field("subscriptionPrice", "Harga pelaksanaan per saham", terms.subscriptionPrice, (value) => onTermsChange("subscriptionPrice", value), "Rp")}
        </div><p className="mt-3 text-xs leading-5 text-gray-500">1 HMETD = 1 saham baru. Jumlah hak yang dibeli tidak dikalikan lagi dengan rasio saham lama. {Number.isSafeInteger(input.rightsQuantity) && input.rightsQuantity > 0 ? `${formatNumber(input.rightsQuantity)} hak = ${formatNumber(input.rightsQuantity / 100, 2)} lot saham baru.` : ""}</p></div>
        <div className="py-5"><h3 className="mb-4 text-base font-semibold text-gray-950">Acuan & Asumsi Harga</h3><div className="grid gap-4 sm:grid-cols-2">
          {field("referencePrice", "Harga saham ex-right / acuan pribadi", draft.referencePrice, (value) => onChange("referencePrice", value), "Rp")}
          {field("bufferPercent", "Buffer diskon minimum", draft.bufferPercent, (value) => onChange("bufferPercent", value), "%")}
          {field("salePrice", "Asumsi harga jual (opsional)", draft.salePrice, (value) => onChange("salePrice", value), "Rp", false, "Mengikuti acuan")}
        </div><p className="mt-3 text-xs leading-5 text-gray-500">Acuan diisi manual untuk saham setelah ex-right, bukan harga cum-right. Label murah / mahal membandingkan modal efektif terhadap acuan bersih setelah fee jual; buffer adalah asumsi pribadi, bukan standar valuasi.</p></div>
        <details className="py-5" open><summary className="cursor-pointer text-sm font-semibold text-gray-950">Biaya Transaksi</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">
          {field("buyFeePercent", "Fee beli HMETD", draft.buyFeePercent, (value) => onChange("buyFeePercent", value), "%")}
          {field("sellFeePercent", "Fee jual saham (termasuk pajak)", draft.sellFeePercent, (value) => onChange("sellFeePercent", value), "%")}
          {field("redemptionFee", "Biaya penebusan tetap total", draft.redemptionFee, (value) => onChange("redemptionFee", value), "Rp")}
        </div><p className="mt-3 text-xs leading-5 text-gray-500">Biaya awal 0; sesuaikan tarif broker. Biaya penebusan tetap dihitung sekali untuk seluruh hak, bukan per saham.</p></details>
      </div>
      <section aria-label="Ringkasan pembelian HMETD" className="min-w-0 border-y border-gray-200 py-5"><h3 className="text-base font-semibold text-gray-950">Modal Efektif & Batas Harga</h3>
        {!calculation ? <div className="mt-5 border-y border-gray-100 py-6 text-sm leading-6 text-gray-500">{nonStandardRight ? "Konversi dokumen tidak didukung." : missing ? "Isi jumlah hak, harga HMETD, harga tebus, dan acuan saham. Tidak perlu memiliki saham lama." : <div role="alert" className="text-red-700">{result.errors.map((error) => <p key={error}>{error}</p>)}</div>}</div> : <>
          <div className={`mt-4 border-l-2 px-3 py-3 ${calculation.status === "cheap" ? "border-emerald-500 bg-emerald-50" : calculation.status === "expensive" ? "border-red-500 bg-red-50" : "border-amber-400 bg-amber-50"}`}><p className={`text-base font-semibold ${tones[calculation.status]}`}>{hmetdBuyerStatusLabels[calculation.status]}</p><p className="mt-1 text-xs leading-5 text-gray-600">Diskon bersih {formatPercentage(calculation.discountPercent)}; buffer yang dipilih {draft.bufferPercent}%. Tidak menilai kualitas bisnis atau kepastian katalis.</p></div>
          <dl className="mt-3 grid grid-cols-2 gap-x-5">{metric("Modal efektif per saham baru", formatCurrency(calculation.effectiveCost, 4))}{metric("Titik impas harga saham (setelah fee)", formatCurrency(calculation.breakEvenStockPrice, 4))}{metric("Batas HMETD untuk buffer diskon", cap(calculation.maxBufferedRightsPrice), "text-emerald-700")}{metric("Batas HMETD impas pada acuan", cap(calculation.maxBreakEvenRightsPrice))}{metric("Dana beli HMETD + fee", formatCurrency(calculation.rightsCost + calculation.buyFee, 2))}{metric("Dana tebus + biaya tetap", formatCurrency(calculation.subscriptionCash + input.redemptionFee, 2))}{metric("Total dana diperlukan", formatCurrency(calculation.totalCost, 2))}{metric("Estimasi P/L pada asumsi jual", `${calculation.profitLoss > 0 ? "+" : ""}${formatCurrency(calculation.profitLoss, 2)}`, calculation.profitLoss < 0 ? "text-red-600" : "text-emerald-700")}</dl>
          <p className="mt-3 text-xs leading-5 text-gray-500">Asumsi jual {formatCurrency(calculation.salePrice, 2)}; hasil jual bersih {formatCurrency(calculation.netSaleProceeds, 2)}. Return {calculation.returnPercent === null ? "tidak tersedia (modal nol)" : formatPercentage(calculation.returnPercent)}.</p>
          <p className="mt-2 text-xs leading-5 text-gray-500">Batas matematis belum disesuaikan ke fraksi harga bursa. Rp0 pada tabel adalah skenario teoretis, bukan harga penawaran yang dijamin tersedia.</p>
          {calculation.maxBreakEvenRightsPrice < 0 ? <p className="mt-4 text-xs leading-5 text-red-700">Bahkan HMETD gratis belum impas pada acuan ini setelah tebus dan biaya. Batas negatif tidak dianggap harga beli Rp0 yang layak.</p> : null}
        </>}
      </section>
    </div>
    {calculation ? <>
      <div role="region" aria-label="Peta harga HMETD" tabIndex={0} className="mt-6 max-w-full overflow-auto rounded-md border border-gray-200"><table className="w-full min-w-[620px] text-sm"><caption className="p-4 text-left font-semibold text-gray-950">Peta Murah / Mahal terhadap Acuan Bersih</caption><thead className="bg-gray-50 text-xs text-gray-500"><tr>{["Harga HMETD / hak", "Modal / saham", "Diskon bersih", "P/L asumsi jual", "Posisi relatif"].map((label) => <th key={label} scope="col" className="px-4 py-3 text-left font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{rows.map((row) => <tr key={row.price} data-rights-price={row.price} className={row.price === input.rightsPrice ? "bg-red-50/50" : ""}><th scope="row" className="px-4 py-3 text-left tabular-nums">{formatCurrency(row.price, 4)}{row.price === input.rightsPrice ? <span className="ml-2 text-xs font-normal text-red-600">Input</span> : null}</th><td className="px-4 py-3 tabular-nums">{formatCurrency(row.calculation.effectiveCost, 4)}</td><td className="px-4 py-3 tabular-nums">{formatPercentage(row.calculation.discountPercent)}</td><td className={`px-4 py-3 tabular-nums ${row.calculation.profitLoss < 0 ? "text-red-600" : "text-emerald-700"}`}>{formatCurrency(row.calculation.profitLoss, 2)}</td><td className={`px-4 py-3 text-xs font-semibold ${tones[row.calculation.status]}`}>{hmetdBuyerStatusLabels[row.calculation.status]}</td></tr>)}</tbody></table></div>
      <section aria-label="Grafik sensitivitas pembeli HMETD" className="mt-6 border-t border-gray-200 pt-5"><h3 className="text-base font-semibold text-gray-950">Sensitivitas Harga Saham Setelah Tebus</h3><div className="mt-4 h-[260px] w-full min-w-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartRows} margin={{ top: 10, right: 15, left: 0, bottom: 12 }}><CartesianGrid stroke="#e5e7eb" strokeDasharray="3 3" /><XAxis dataKey="price" type="number" domain={["dataMin", "dataMax"]} tickFormatter={(value: number) => formatNumber(value, 1)} tick={{ fontSize: 11 }} /><YAxis width={64} tickFormatter={(value: number) => formatNumber(value / 1000, 1) + "rb"} tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => [formatCurrency(Number(value), 2), "P/L bersih"]} labelFormatter={(label) => `Harga saham ${formatCurrency(Number(label), 2)}`} /><ReferenceLine y={0} stroke="#9ca3af" /><ReferenceLine x={calculation.breakEvenStockPrice} stroke="#d97706" strokeDasharray="4 4" /><Line dataKey="profit" type="linear" stroke="#dc2626" strokeWidth={2} dot={{ r: 3 }} isAnimationActive={false} /></LineChart></ResponsiveContainer></div><p className="mt-2 text-xs text-gray-500">Sumbu X: asumsi harga saham (Rp). Sumbu Y: P/L bersih (ribu Rp). Garis vertikal: titik impas.</p></section>
    </> : null}
    <div className="mt-6 flex gap-2 border-l-2 border-amber-400 bg-amber-50 px-3 py-3"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-700" /><p className="text-xs leading-5 text-amber-900">Modal per saham = harga HMETD x (1 + fee beli) + harga tebus + biaya tetap / jumlah hak. Batas buffer memakai acuan setelah fee jual x (1 - buffer). Harga saham bisa berubah sebelum saham baru masuk rekening; ada risiko likuiditas, jadwal, dan HMETD kedaluwarsa. Diskon matematis bukan keuntungan pasti atau valuasi fundamental.</p></div>
  </section>;
}
